.TH "A4988" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A4988
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <a4988\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsteps_per_rev\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBdir_port\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBstep_port\fP"
.br
.ti -1c
.RI "uint32_t \fBdir_pin\fP"
.br
.ti -1c
.RI "uint32_t \fBstep_pin\fP"
.br
.ti -1c
.RI "float \fBomega\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file a4988\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t A4988::dir_pin"

.PP
Definition at line 19 of file a4988\&.h\&.
.SS "GPIO_TypeDef* A4988::dir_port"

.PP
Definition at line 18 of file a4988\&.h\&.
.SS "float A4988::omega"

.PP
Definition at line 20 of file a4988\&.h\&.
.SS "uint32_t A4988::step_pin"

.PP
Definition at line 19 of file a4988\&.h\&.
.SS "GPIO_TypeDef * A4988::step_port"

.PP
Definition at line 18 of file a4988\&.h\&.
.SS "uint32_t A4988::steps_per_rev"

.PP
Definition at line 17 of file a4988\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
