.TH "Inc/utils Directory Reference" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdefines\&.h\fP"
.br
.ti -1c
.RI "file \fBkalman\&.h\fP"
.br
.ti -1c
.RI "file \fBmat\&.h\fP"
.br
.ti -1c
.RI "file \fBpid\&.h\fP"
.br
.ti -1c
.RI "file \fBpid_algorithms\&.h\fP"
.br
.ti -1c
.RI "file \fBsmoothing_algorithm\&.h\fP"
.br
.ti -1c
.RI "file \fBvec2\&.h\fP"
.br
.ti -1c
.RI "file \fBvec3\&.h\fP"
.br
.ti -1c
.RI "file \fBvec4\&.h\fP"
.br
.in -1c
