.TH "Src/utils Directory Reference" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexp_smooth\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmat\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprintf_config\&.c\fP"
.br
.in -1c
