.TH "Inc/devs Directory Reference" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBa4988\&.h\fP"
.br
.ti -1c
.RI "file \fBencoder\&.h\fP"
.br
.ti -1c
.RI "file \fBhmc5883\&.h\fP"
.br
.ti -1c
.RI "file \fBleg\&.h\fP"
.br
.ti -1c
.RI "file \fBlimit_switch\&.h\fP"
.br
.ti -1c
.RI "file \fBmotor\&.h\fP"
.br
.ti -1c
.RI "file \fBmpu6050\&.h\fP"
.br
.ti -1c
.RI "file \fBmpu6050_reg\&.h\fP"
.br
.ti -1c
.RI "file \fBsteering\&.h\fP"
.br
.in -1c
