.TH "Exp_Smooth" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exp_Smooth
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smoothing_algorithm\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExp_Smooth\fP ()"
.br
.ti -1c
.RI "\fBExp_Smooth\fP (float alpha)"
.br
.ti -1c
.RI "\fBExp_Smooth\fP (\fBExp_Smooth\fP &&)=default"
.br
.ti -1c
.RI "\fBExp_Smooth\fP (const \fBExp_Smooth\fP &)=default"
.br
.ti -1c
.RI "\fBExp_Smooth\fP & \fBoperator=\fP (\fBExp_Smooth\fP &&)=default"
.br
.ti -1c
.RI "\fBExp_Smooth\fP & \fBoperator=\fP (const \fBExp_Smooth\fP &)=default"
.br
.ti -1c
.RI "\fB~Exp_Smooth\fP ()"
.br
.ti -1c
.RI "void \fBset_Alpha\fP (float alpha)"
.br
.ti -1c
.RI "float \fBsmooth\fP (const float &input)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBlast_output_\fP"
.br
.ti -1c
.RI "float \fBalpha_\fP"
.br
.ti -1c
.RI "bool \fBis_first_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file smoothing_algorithm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Exp_Smooth::Exp_Smooth ()"

.PP
Definition at line 12 of file exp_smooth\&.cpp\&.
.SS "Exp_Smooth::Exp_Smooth (float alpha)"

.PP
Definition at line 18 of file exp_smooth\&.cpp\&.
.SS "Exp_Smooth::Exp_Smooth (\fBExp_Smooth\fP &&)\fC [default]\fP"

.SS "Exp_Smooth::Exp_Smooth (const \fBExp_Smooth\fP &)\fC [default]\fP"

.SS "Exp_Smooth::~Exp_Smooth ()\fC [inline]\fP"

.PP
Definition at line 17 of file smoothing_algorithm\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Exp_Smooth::clear ()"

.PP
Definition at line 38 of file exp_smooth\&.cpp\&.
.SS "\fBExp_Smooth\fP& Exp_Smooth::operator= (\fBExp_Smooth\fP &&)\fC [default]\fP"

.SS "\fBExp_Smooth\fP& Exp_Smooth::operator= (const \fBExp_Smooth\fP &)\fC [default]\fP"

.SS "void Exp_Smooth::set_Alpha (float alpha)\fC [inline]\fP"

.PP
Definition at line 19 of file smoothing_algorithm\&.h\&.
.SS "float Exp_Smooth::smooth (const float & input)"

.PP
Definition at line 24 of file exp_smooth\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "float Exp_Smooth::alpha_\fC [private]\fP"

.PP
Definition at line 27 of file smoothing_algorithm\&.h\&.
.SS "bool Exp_Smooth::is_first_\fC [private]\fP"

.PP
Definition at line 28 of file smoothing_algorithm\&.h\&.
.SS "float Exp_Smooth::last_output_\fC [private]\fP"

.PP
Definition at line 26 of file smoothing_algorithm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
