.TH "HMC5883" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HMC5883
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hmc5883\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "I2C_HandleTypeDef * \fBhi2c\fP"
.br
.ti -1c
.RI "\fBVec3\fP< float > \fBraw_axis\fP"
.br
.ti -1c
.RI "uint8_t \fBaddress\fP"
.br
.ti -1c
.RI "\fBVec3\fP< float > \fBhard_iron_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file hmc5883\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t HMC5883::address"

.PP
Definition at line 21 of file hmc5883\&.h\&.
.SS "\fBVec3\fP<float> HMC5883::hard_iron_offset"

.PP
Definition at line 22 of file hmc5883\&.h\&.
.SS "I2C_HandleTypeDef* HMC5883::hi2c"

.PP
Definition at line 19 of file hmc5883\&.h\&.
.SS "\fBVec3\fP<float> HMC5883::raw_axis"

.PP
Definition at line 20 of file hmc5883\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
