.TH "Src/devs/hmc5883.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/devs/hmc5883.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'hmc5883\&.h'\fP
.br
\fC#include 'mpu6050\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int8_t \fBHMC5883_Init\fP (struct \fBHMC5883\fP *hmc)"
.br
.ti -1c
.RI "int8_t \fBHMC5883_Read\fP (struct \fBHMC5883\fP *hmc)"
.br
.ti -1c
.RI "static float \fBmax_val\fP (float x, float y)"
.br
.ti -1c
.RI "static float \fBmin_val\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBHMC5883_Calibrate\fP (struct \fBHMC5883\fP *hmc, struct \fBA4988\fP *stpr, uint32_t n)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static uint8_t \fBbuffer\fP [8]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HMC5883_Calibrate (struct \fBHMC5883\fP * hmc, struct \fBA4988\fP * stpr, uint32_t n)"

.PP
Definition at line 61 of file hmc5883\&.cpp\&.
.SS "int8_t HMC5883_Init (struct \fBHMC5883\fP * hmc)"

.PP
Definition at line 15 of file hmc5883\&.cpp\&.
.SS "int8_t HMC5883_Read (struct \fBHMC5883\fP * hmc)"

.PP
Definition at line 32 of file hmc5883\&.cpp\&.
.SS "static float max_val (float x, float y)\fC [static]\fP"

.PP
Definition at line 51 of file hmc5883\&.cpp\&.
.SS "static float min_val (float x, float y)\fC [static]\fP"

.PP
Definition at line 56 of file hmc5883\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t buffer[8]\fC [static]\fP"

.PP
Definition at line 13 of file hmc5883\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
