.TH "Src/periphs/i2c.c" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/periphs/i2c.c
.SH SYNOPSIS
.br
.PP
\fC#include 'i2c\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_I2C1_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_I2C2_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MspInit\fP (I2C_HandleTypeDef *i2cHandle)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MspDeInit\fP (I2C_HandleTypeDef *i2cHandle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "I2C_HandleTypeDef \fBhi2c1\fP"
.br
.ti -1c
.RI "I2C_HandleTypeDef \fBhi2c2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HAL_I2C_MspDeInit (I2C_HandleTypeDef * i2cHandle)"
I2C1 GPIO Configuration
.PP
PB8 ------> I2C1_SCL PB9 ------> I2C1_SDA
.PP
I2C2 GPIO Configuration
.PP
PB10 ------> I2C2_SCL PB11 ------> I2C2_SDA
.PP
Definition at line 143 of file i2c\&.c\&.
.SS "void HAL_I2C_MspInit (I2C_HandleTypeDef * i2cHandle)"
I2C1 GPIO Configuration
.PP
PB8 ------> I2C1_SCL PB9 ------> I2C1_SDA
.PP
I2C2 GPIO Configuration
.PP
PB10 ------> I2C2_SCL PB11 ------> I2C2_SDA
.PP
Definition at line 89 of file i2c\&.c\&.
.SS "void MX_I2C1_Init (void)"

.PP
Definition at line 51 of file i2c\&.c\&.
.SS "void MX_I2C2_Init (void)"

.PP
Definition at line 70 of file i2c\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "I2C_HandleTypeDef hi2c1"
File Name : \fBI2C\&.c\fP Description : This file provides code for the configuration of the I2C instances\&.
.PP
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2019 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.PP
Definition at line 47 of file i2c\&.c\&.
.SS "I2C_HandleTypeDef hi2c2"

.PP
Definition at line 48 of file i2c\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
