.TH "Kalman_Vars" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kalman_Vars
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kalman\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_F\fP (const \fBMat\fP &f)"
.br
.ti -1c
.RI "void \fBset_B\fP (const \fBMat\fP &b)"
.br
.ti -1c
.RI "void \fBset_H\fP (const \fBMat\fP &h)"
.br
.ti -1c
.RI "void \fBset_I\fP (uint8_t n)"
.br
.ti -1c
.RI "void \fBset_P\fP (const \fBMat\fP &p)"
.br
.ti -1c
.RI "void \fBset_Q\fP (const \fBMat\fP &q)"
.br
.ti -1c
.RI "void \fBset_R\fP (const \fBMat\fP &r)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBMat\fP \fBF_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBB_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBH_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBI_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBP_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBQ_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBR_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBKalman_Filter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file kalman\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Kalman_Vars::set_B (const \fBMat\fP & b)\fC [inline]\fP"

.PP
Definition at line 20 of file kalman\&.h\&.
.SS "void Kalman_Vars::set_F (const \fBMat\fP & f)\fC [inline]\fP"

.PP
Definition at line 19 of file kalman\&.h\&.
.SS "void Kalman_Vars::set_H (const \fBMat\fP & h)\fC [inline]\fP"

.PP
Definition at line 21 of file kalman\&.h\&.
.SS "void Kalman_Vars::set_I (uint8_t n)\fC [inline]\fP"

.PP
Definition at line 22 of file kalman\&.h\&.
.SS "void Kalman_Vars::set_P (const \fBMat\fP & p)\fC [inline]\fP"

.PP
Definition at line 23 of file kalman\&.h\&.
.SS "void Kalman_Vars::set_Q (const \fBMat\fP & q)\fC [inline]\fP"

.PP
Definition at line 24 of file kalman\&.h\&.
.SS "void Kalman_Vars::set_R (const \fBMat\fP & r)\fC [inline]\fP"

.PP
Definition at line 25 of file kalman\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBKalman_Filter\fP\fC [friend]\fP"

.PP
Definition at line 27 of file kalman\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMat\fP Kalman_Vars::B_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Vars::F_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Vars::H_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Vars::I_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Vars::P_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Vars::Q_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Vars::R_\fC [private]\fP"

.PP
Definition at line 30 of file kalman\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
