.TH "Kalman_Filter" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kalman_Filter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kalman\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKalman_Filter\fP (\fBKalman_Vars\fP *kv, int(*kv_init)(uint32_t))"
.br
.ti -1c
.RI "\fBKalman_Filter\fP (\fBKalman_Filter\fP &&)=default"
.br
.ti -1c
.RI "\fBKalman_Filter\fP (const \fBKalman_Filter\fP &)=default"
.br
.ti -1c
.RI "\fBKalman_Filter\fP & \fBoperator=\fP (\fBKalman_Filter\fP &&)=default"
.br
.ti -1c
.RI "\fBKalman_Filter\fP & \fBoperator=\fP (const \fBKalman_Filter\fP &)=default"
.br
.ti -1c
.RI "\fB~Kalman_Filter\fP ()"
.br
.ti -1c
.RI "float \fBfilter\fP (float measured, float control_input, uint32_t dt_millis)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int(* \fBkv_init_\fP )(uint32_t)"
.br
.ti -1c
.RI "bool \fBis_first_\fP"
.br
.ti -1c
.RI "\fBKalman_Vars\fP * \fBkv_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBx_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBu_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBz_\fP"
.br
.ti -1c
.RI "\fBMat\fP \fBK_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file kalman\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Kalman_Filter::Kalman_Filter (\fBKalman_Vars\fP * kv, int(*)(uint32_t) kv_init)\fC [inline]\fP"

.PP
Definition at line 37 of file kalman\&.h\&.
.SS "Kalman_Filter::Kalman_Filter (\fBKalman_Filter\fP &&)\fC [default]\fP"

.SS "Kalman_Filter::Kalman_Filter (const \fBKalman_Filter\fP &)\fC [default]\fP"

.SS "Kalman_Filter::~Kalman_Filter ()\fC [inline]\fP"

.PP
Definition at line 48 of file kalman\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Kalman_Filter::clear ()\fC [inline]\fP"

.PP
Definition at line 78 of file kalman\&.h\&.
.SS "float Kalman_Filter::filter (float measured, float control_input, uint32_t dt_millis)\fC [inline]\fP"

.PP
Definition at line 50 of file kalman\&.h\&.
.SS "\fBKalman_Filter\fP& Kalman_Filter::operator= (\fBKalman_Filter\fP &&)\fC [default]\fP"

.SS "\fBKalman_Filter\fP& Kalman_Filter::operator= (const \fBKalman_Filter\fP &)\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool Kalman_Filter::is_first_\fC [private]\fP"

.PP
Definition at line 84 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Filter::K_\fC [private]\fP"

.PP
Definition at line 87 of file kalman\&.h\&.
.SS "\fBKalman_Vars\fP* Kalman_Filter::kv_\fC [private]\fP"

.PP
Definition at line 85 of file kalman\&.h\&.
.SS "int(* Kalman_Filter::kv_init_) (uint32_t)\fC [private]\fP"

.PP
Definition at line 83 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Filter::u_\fC [private]\fP"

.PP
Definition at line 87 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Filter::x_\fC [private]\fP"

.PP
Definition at line 87 of file kalman\&.h\&.
.SS "\fBMat\fP Kalman_Filter::z_\fC [private]\fP"

.PP
Definition at line 87 of file kalman\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
