.TH "Inc/devs/leg.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/leg.h
.SH SYNOPSIS
.br
.PP
\fC#include 'motor\&.h'\fP
.br
\fC#include 'encoder\&.h'\fP
.br
\fC#include 'pid\&.h'\fP
.br
\fC#include 'limit_switch\&.h'\fP
.br
\fC#include 'defines\&.h'\fP
.br
\fC#include 'pid_algorithms\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleg\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLeg_condition\fP { \fBRAISED\fP, \fBFALLEN\fP, \fBUNDEFINED\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLeg_condition\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRAISED \fP\fP
.TP
\fB\fIFALLEN \fP\fP
.TP
\fB\fIUNDEFINED \fP\fP
.PP
Definition at line 11 of file leg\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
