.TH "Inc/main.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/main.h \- : Header for main\&.c file\&. This file contains the common defines of the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMOTOR3_OUT_Pin\fP   GPIO_PIN_10"
.br
.ti -1c
.RI "#define \fBMOTOR3_OUT_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBMOTOR1_OUT_Pin\fP   GPIO_PIN_15"
.br
.ti -1c
.RI "#define \fBMOTOR1_OUT_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBMOTOR1_OUTC11_Pin\fP   GPIO_PIN_11"
.br
.ti -1c
.RI "#define \fBMOTOR1_OUTC11_GPIO_Port\fP   GPIOC"
.br
.ti -1c
.RI "#define \fBMOTOR2_OUT_Pin\fP   GPIO_PIN_2"
.br
.ti -1c
.RI "#define \fBMOTOR2_OUT_GPIO_Port\fP   GPIOD"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBError_Handler\fP (void)"
.br
.RI "This function is executed in case of error occurrence\&. "
.ti -1c
.RI "void \fB_Error_Handler\fP (const char *file, size_t line)"
.br
.in -1c
.SH "Detailed Description"
.PP 
: Header for main\&.c file\&. This file contains the common defines of the application\&. 

This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2019 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.PP
Definition in file \fBmain\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MOTOR1_OUT_GPIO_Port   GPIOA"

.PP
Definition at line 86 of file main\&.h\&.
.SS "#define MOTOR1_OUT_Pin   GPIO_PIN_15"

.PP
Definition at line 85 of file main\&.h\&.
.SS "#define MOTOR1_OUTC11_GPIO_Port   GPIOC"

.PP
Definition at line 88 of file main\&.h\&.
.SS "#define MOTOR1_OUTC11_Pin   GPIO_PIN_11"

.PP
Definition at line 87 of file main\&.h\&.
.SS "#define MOTOR2_OUT_GPIO_Port   GPIOD"

.PP
Definition at line 90 of file main\&.h\&.
.SS "#define MOTOR2_OUT_Pin   GPIO_PIN_2"

.PP
Definition at line 89 of file main\&.h\&.
.SS "#define MOTOR3_OUT_GPIO_Port   GPIOA"

.PP
Definition at line 84 of file main\&.h\&.
.SS "#define MOTOR3_OUT_Pin   GPIO_PIN_10"

.PP
Definition at line 83 of file main\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void _Error_Handler (const char * file, size_t line)"

.PP
Definition at line 219 of file main\&.cpp\&.
.SS "void Error_Handler (void)"

.PP
This function is executed in case of error occurrence\&. 
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 211 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
