.TH "Src/utils/mat.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/utils/mat.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mat\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap\fP (\fBMat\fP &first, \fBMat\fP &second)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void swap (\fBMat\fP & first, \fBMat\fP & second)"

.PP
Definition at line 38 of file mat\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
