.TH "Inc/devs/motor.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/motor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br
\fC#include 'tim\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmotor_config\fP"
.br
.ti -1c
.RI "class \fBmotor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDirection\fP { \fBCLOCKWISE\fP, \fBANTICLOCKWISE\fP, \fBSTOP\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDirection\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICLOCKWISE \fP\fP
.TP
\fB\fIANTICLOCKWISE \fP\fP
.TP
\fB\fISTOP \fP\fP
.PP
Definition at line 8 of file motor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
