.TH "MPU6050" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPU6050
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpu6050\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "I2C_HandleTypeDef * \fBhi2c\fP"
.br
.ti -1c
.RI "\fBVec3\fP< int16_t > \fBraw_g_axis\fP"
.br
.ti -1c
.RI "\fBVec3\fP< int16_t > \fBraw_a_axis\fP"
.br
.ti -1c
.RI "\fBVec3\fP< float > \fBnorm_g_axis\fP"
.br
.ti -1c
.RI "\fBVec3\fP< float > \fBnorm_a_axis\fP"
.br
.ti -1c
.RI "uint8_t \fBaddress\fP"
.br
.ti -1c
.RI "float \fBtmpr\fP"
.br
.ti -1c
.RI "enum \fBAccel_Scale\fP \fBa_scale\fP"
.br
.ti -1c
.RI "enum \fBGyro_Scale\fP \fBg_scale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file mpu6050\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "enum \fBAccel_Scale\fP MPU6050::a_scale"

.PP
Definition at line 41 of file mpu6050\&.h\&.
.SS "uint8_t MPU6050::address"

.PP
Definition at line 39 of file mpu6050\&.h\&.
.SS "enum \fBGyro_Scale\fP MPU6050::g_scale"

.PP
Definition at line 42 of file mpu6050\&.h\&.
.SS "I2C_HandleTypeDef* MPU6050::hi2c"

.PP
Definition at line 36 of file mpu6050\&.h\&.
.SS "\fBVec3\fP<float> MPU6050::norm_a_axis"

.PP
Definition at line 38 of file mpu6050\&.h\&.
.SS "\fBVec3\fP<float> MPU6050::norm_g_axis"

.PP
Definition at line 38 of file mpu6050\&.h\&.
.SS "\fBVec3\fP<int16_t> MPU6050::raw_a_axis"

.PP
Definition at line 37 of file mpu6050\&.h\&.
.SS "\fBVec3\fP<int16_t> MPU6050::raw_g_axis"

.PP
Definition at line 37 of file mpu6050\&.h\&.
.SS "float MPU6050::tmpr"

.PP
Definition at line 40 of file mpu6050\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
