.TH "Inc/devs/mpu6050.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/mpu6050.h
.SH SYNOPSIS
.br
.PP
\fC#include 'vec3\&.h'\fP
.br
\fC#include 'i2c\&.h'\fP
.br
\fC#include 'mpu6050_reg\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMPU6050\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2C_TIMEOUT\fP   (5)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAccel_Scale\fP { \fBSCALE_2G\fP = 0, \fBSCALE_4G\fP, \fBSCALE_8G\fP, \fBSCALE_16G\fP }"
.br
.ti -1c
.RI "enum \fBGyro_Scale\fP { \fBSCALE_250\fP = 0, \fBSCALE_500\fP, \fBSCALE_1000\fP, \fBSCALE_2000\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int8_t \fBMPU6050_Init\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_Temp\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_RawAccel\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_RawGyro\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_RawAxes\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_NormAccel\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_NormGyro\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "int8_t \fBMPU6050_Read_NormAxes\fP (struct \fBMPU6050\fP *mpu)"
.br
.ti -1c
.RI "\fBVec3\fP< float > \fBMPU6050_Calc_OmegaBias\fP (struct \fBMPU6050\fP *mpu, uint32_t n)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define I2C_TIMEOUT   (5)"

.PP
Definition at line 16 of file mpu6050\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAccel_Scale\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISCALE_2G \fP\fP
.TP
\fB\fISCALE_4G \fP\fP
.TP
\fB\fISCALE_8G \fP\fP
.TP
\fB\fISCALE_16G \fP\fP
.PP
Definition at line 18 of file mpu6050\&.h\&.
.SS "enum \fBGyro_Scale\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISCALE_250 \fP\fP
.TP
\fB\fISCALE_500 \fP\fP
.TP
\fB\fISCALE_1000 \fP\fP
.TP
\fB\fISCALE_2000 \fP\fP
.PP
Definition at line 26 of file mpu6050\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBVec3\fP<float> MPU6050_Calc_OmegaBias (struct \fBMPU6050\fP * mpu, uint32_t n)"

.PP
Definition at line 140 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Init (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 20 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_NormAccel (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 94 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_NormAxes (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 132 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_NormGyro (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 115 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_RawAccel (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 45 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_RawAxes (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 86 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_RawGyro (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 59 of file mpu6050\&.cpp\&.
.SS "int8_t MPU6050_Read_Temp (struct \fBMPU6050\fP * mpu)"

.PP
Definition at line 73 of file mpu6050\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
