.TH "PID" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pid\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPID\fP ()"
.br
.ti -1c
.RI "\fBPID\fP (\fBPID_Algorithm\fP *algo)"
.br
.ti -1c
.RI "\fBPID\fP (\fBPID\fP &&)=default"
.br
.ti -1c
.RI "\fBPID\fP (const \fBPID\fP &)=default"
.br
.ti -1c
.RI "\fBPID\fP & \fBoperator=\fP (\fBPID\fP &&)=default"
.br
.ti -1c
.RI "\fBPID\fP & \fBoperator=\fP (const \fBPID\fP &)=default"
.br
.ti -1c
.RI "\fB~PID\fP ()"
.br
.ti -1c
.RI "void \fBset_Algorithm\fP (\fBPID_Algorithm\fP *algo)"
.br
.ti -1c
.RI "\fBPID_Algorithm\fP * \fBget_Algorithm\fP ()"
.br
.ti -1c
.RI "float \fBcompute_PID\fP (float err, uint32_t dt_millis)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPID_Algorithm\fP * \fBalgo_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file pid\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PID::PID ()\fC [inline]\fP"

.PP
Definition at line 9 of file pid\&.h\&.
.SS "PID::PID (\fBPID_Algorithm\fP * algo)\fC [inline]\fP"

.PP
Definition at line 10 of file pid\&.h\&.
.SS "PID::PID (\fBPID\fP &&)\fC [default]\fP"

.SS "PID::PID (const \fBPID\fP &)\fC [default]\fP"

.SS "PID::~PID ()\fC [inline]\fP"

.PP
Definition at line 15 of file pid\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "float PID::compute_PID (float err, uint32_t dt_millis)\fC [inline]\fP"

.PP
Definition at line 19 of file pid\&.h\&.
.SS "\fBPID_Algorithm\fP* PID::get_Algorithm ()\fC [inline]\fP"

.PP
Definition at line 18 of file pid\&.h\&.
.SS "\fBPID\fP& PID::operator= (\fBPID\fP &&)\fC [default]\fP"

.SS "\fBPID\fP& PID::operator= (const \fBPID\fP &)\fC [default]\fP"

.SS "void PID::set_Algorithm (\fBPID_Algorithm\fP * algo)\fC [inline]\fP"

.PP
Definition at line 17 of file pid\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPID_Algorithm\fP* PID::algo_\fC [private]\fP"

.PP
Definition at line 24 of file pid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
