.TH "Src/robot/robo_init.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/robot/robo_init.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'robo_init\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBmotor_init\fP ()"
.br
.ti -1c
.RI "static void \fBencoder_init\fP ()"
.br
.ti -1c
.RI "static void \fBpid_init\fP ()"
.br
.ti -1c
.RI "static void \fBlimit_switch_init\fP ()"
.br
.ti -1c
.RI "static void \fBleg_init\fP ()"
.br
.ti -1c
.RI "static void \fBsteering_init\fP ()"
.br
.ti -1c
.RI "void \fBrobo_init\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBleg\fP \fBleg\fP [2]"
.br
.ti -1c
.RI "\fBsteering\fP \fBsteering\fP"
.br
.ti -1c
.RI "static \fBmotor_config\fP \fBmotor_configurations\fP [3]"
.br
.ti -1c
.RI "static \fBencoder_config\fP \fBencoder_configurations\fP [3]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void encoder_init ()\fC [static]\fP"

.PP
Definition at line 92 of file robo_init\&.cpp\&.
.SS "void leg_init ()\fC [static]\fP"

.PP
Definition at line 26 of file robo_init\&.cpp\&.
.SS "static void limit_switch_init ()\fC [static]\fP"

.PP
Definition at line 47 of file robo_init\&.cpp\&.
.SS "void motor_init ()\fC [static]\fP"

.PP
Definition at line 57 of file robo_init\&.cpp\&.
.SS "static void pid_init ()\fC [static]\fP"

.PP
Definition at line 38 of file robo_init\&.cpp\&.
.SS "void robo_init (void)"

.PP
Definition at line 17 of file robo_init\&.cpp\&.
.SS "void steering_init ()\fC [static]\fP"

.PP
Definition at line 34 of file robo_init\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBencoder_config\fP encoder_configurations[3]\fC [static]\fP"

.PP
Definition at line 7 of file robo_init\&.cpp\&.
.SS "\fBleg\fP \fBleg\fP[2]"

.PP
Definition at line 3 of file robo_init\&.cpp\&.
.SS "\fBmotor_config\fP motor_configurations[3]\fC [static]\fP"

.PP
Definition at line 6 of file robo_init\&.cpp\&.
.SS "\fBsteering\fP \fBsteering\fP"

.PP
Definition at line 4 of file robo_init\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
