.TH "Src/robot/robo_orientation.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/robot/robo_orientation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'smoothing_algorithm\&.h'\fP
.br
\fC#include 'kalman\&.h'\fP
.br
\fC#include 'mpu6050\&.h'\fP
.br
\fC#include 'hmc5883\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_OriFilters\fP (uint32_t dt_millis)"
.br
.ti -1c
.RI "static void \fBIMU_Init\fP ()"
.br
.ti -1c
.RI "int \fBAngle_Init\fP ()"
.br
.ti -1c
.RI "\fBVec3\fP< float > \fBread_Orientation\fP (uint32_t dt_millis)"
.br
.RI "Function that provides the orientation of the robot\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBMPU6050\fP \fBBody_IMU\fP"
.br
.ti -1c
.RI "struct \fBHMC5883\fP \fBBody_HMC\fP"
.br
.ti -1c
.RI "static \fBVec3\fP< float > \fBgOmega_Bias\fP"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgXAccelAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgYAccelAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgZAccelAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgXGyroAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgYGyroAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgZGyroAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgXMagAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgYMagAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBExp_Smooth\fP \fBgZMagAlpha35\fP (0\&.035)"
.br
.ti -1c
.RI "static \fBKalman_Vars\fP \fBgAccel_Gyro\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Angle_Init ()"

.PP
Definition at line 47 of file robo_orientation\&.cpp\&.
.SS "static void IMU_Init ()\fC [static]\fP"

.PP
Definition at line 32 of file robo_orientation\&.cpp\&.
.SS "int init_OriFilters (uint32_t dt_millis)"

.PP
Definition at line 56 of file robo_orientation\&.cpp\&.
.SS "\fBVec3\fP<float> read_Orientation (uint32_t dt_millis)"

.PP
Function that provides the orientation of the robot\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbase_state\fP This parameter is considered as one of the possible state of robot\&. 
.br
\fIdt_millis\fP : The time period at which this function is called periodically
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIorientation\fP of the robot in degrees
.RE
.PP
.PP
.nf

Tasks performed by this function
1) Read the values from Accelerometer and the Gyroscope
.fi
.PP
 
.PP
Definition at line 117 of file robo_orientation\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBHMC5883\fP Body_HMC"

.PP
Definition at line 10 of file robo_orientation\&.cpp\&.
.SS "struct \fBMPU6050\fP Body_IMU"

.PP
Definition at line 9 of file robo_orientation\&.cpp\&.
.SS "static \fBKalman_Filter\fP gYaw_Filter & gAccel_Gyro\fC [static]\fP"

.PP
Definition at line 26 of file robo_orientation\&.cpp\&.
.SS "\fBVec3\fP<float> gOmega_Bias\fC [static]\fP"

.PP
Definition at line 12 of file robo_orientation\&.cpp\&.
.SS "\fBExp_Smooth\fP gXAccelAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gXGyroAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gXMagAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gYAccelAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gYGyroAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gYMagAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gZAccelAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gZGyroAlpha35(0\&.035)\fC [static]\fP"

.SS "\fBExp_Smooth\fP gZMagAlpha35(0\&.035)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
