.TH "Inc/utils/smoothing_algorithm.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/utils/smoothing_algorithm.h
.SH SYNOPSIS
.br
.PP
\fC#include 'vec3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExp_Smooth\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
