.TH "Src/periphs/usart.c" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/periphs/usart.c
.SH SYNOPSIS
.br
.PP
\fC#include 'usart\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_USART1_UART_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_USART2_UART_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_UART_MspInit\fP (UART_HandleTypeDef *uartHandle)"
.br
.ti -1c
.RI "void \fBHAL_UART_MspDeInit\fP (UART_HandleTypeDef *uartHandle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "UART_HandleTypeDef \fBhuart1\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef \fBhuart2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HAL_UART_MspDeInit (UART_HandleTypeDef * uartHandle)"
USART1 GPIO Configuration
.PP
PB6 ------> USART1_TX PB7 ------> USART1_RX
.PP
USART2 GPIO Configuration
.PP
PD5 ------> USART2_TX PD6 ------> USART2_RX
.PP
Definition at line 143 of file usart\&.c\&.
.SS "void HAL_UART_MspInit (UART_HandleTypeDef * uartHandle)"
USART1 GPIO Configuration
.PP
PB6 ------> USART1_TX PB7 ------> USART1_RX
.PP
USART2 GPIO Configuration
.PP
PD5 ------> USART2_TX PD6 ------> USART2_RX
.PP
Definition at line 89 of file usart\&.c\&.
.SS "void MX_USART1_UART_Init (void)"

.PP
Definition at line 52 of file usart\&.c\&.
.SS "void MX_USART2_UART_Init (void)"

.PP
Definition at line 71 of file usart\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "UART_HandleTypeDef huart1"
File Name : \fBUSART\&.c\fP Description : This file provides code for the configuration of the USART instances\&.
.PP
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2019 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.PP
Definition at line 47 of file usart\&.c\&.
.SS "UART_HandleTypeDef huart2"

.PP
Definition at line 48 of file usart\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
