.TH "Vec3< T >" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec3< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vec3\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec3\fP ()"
.br
.ti -1c
.RI "\fBVec3\fP (T x, T y, T z)"
.br
.ti -1c
.RI "\fBVec3\fP (\fBVec3\fP &&)=default"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator=\fP (\fBVec3\fP &&)=default"
.br
.ti -1c
.RI "\fB~Vec3\fP ()"
.br
.ti -1c
.RI "T \fBgetX\fP () const"
.br
.ti -1c
.RI "T \fBgetY\fP () const"
.br
.ti -1c
.RI "T \fBgetZ\fP () const"
.br
.ti -1c
.RI "void \fBsetX\fP (T x)"
.br
.ti -1c
.RI "void \fBsetY\fP (T y)"
.br
.ti -1c
.RI "void \fBsetZ\fP (T z)"
.br
.ti -1c
.RI "void \fBset_Values\fP (T x, T y, T z)"
.br
.ti -1c
.RI "\fBVec3\fP \fBmult_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec3\fP \fBmult_EW\fP (\fBVec3\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec3\fP \fBadd_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec3\fP \fBadd_EW\fP (\fBVec3\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec3\fP \fBsub_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec3\fP \fBsub_EW\fP (\fBVec3\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec3\fP \fBdiv_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec3\fP \fBdiv_EW\fP (\fBVec3\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec3\fP (const \fBVec3\fP &v)"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator=\fP (const \fBVec3\fP &v)"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator+=\fP (const \fBVec3\fP &rhs)"
.br
.ti -1c
.RI "\fBVec3\fP & \fBoperator\-=\fP (const \fBVec3\fP &rhs)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBx_\fP"
.br
.ti -1c
.RI "T \fBy_\fP"
.br
.ti -1c
.RI "T \fBz_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBVec3\fP \fBoperator+\fP (\fBVec3\fP lhs, const \fBVec3\fP &rhs)"
.br
.ti -1c
.RI "\fBVec3\fP \fBoperator\-\fP (\fBVec3\fP lhs, const \fBVec3\fP &rhs)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBVec3\fP &first, \fBVec3\fP &second)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class Vec3< T >"

.PP
Definition at line 24 of file vec3\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBVec3\fP< T >::\fBVec3\fP ()\fC [inline]\fP"

.PP
Definition at line 27 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP< T >::\fBVec3\fP (T x, T y, T z)\fC [inline]\fP"

.PP
Definition at line 28 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP< T >::\fBVec3\fP (\fBVec3\fP< T > &&)\fC [default]\fP"

.SS "template<class T> \fBVec3\fP< T >::~\fBVec3\fP ()\fC [inline]\fP"

.PP
Definition at line 32 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP< T >::\fBVec3\fP (const \fBVec3\fP< T > & v)\fC [inline]\fP"

.PP
Definition at line 128 of file vec3\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T> \fBVec3\fP \fBVec3\fP< T >::add_EW (float num)\fC [inline]\fP"

.PP
Definition at line 68 of file vec3\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec3\fP \fBVec3\fP< T >::add_EW (\fBVec3\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 78 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP \fBVec3\fP< T >::div_EW (float num)\fC [inline]\fP"

.PP
Definition at line 108 of file vec3\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec3\fP \fBVec3\fP< T >::div_EW (\fBVec3\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 118 of file vec3\&.h\&.
.SS "template<class T> T \fBVec3\fP< T >::getX () const\fC [inline]\fP"

.PP
Definition at line 34 of file vec3\&.h\&.
.SS "template<class T> T \fBVec3\fP< T >::getY () const\fC [inline]\fP"

.PP
Definition at line 35 of file vec3\&.h\&.
.SS "template<class T> T \fBVec3\fP< T >::getZ () const\fC [inline]\fP"

.PP
Definition at line 36 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP \fBVec3\fP< T >::mult_EW (float num)\fC [inline]\fP"

.PP
Definition at line 48 of file vec3\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec3\fP \fBVec3\fP< T >::mult_EW (\fBVec3\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 58 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP& \fBVec3\fP< T >::operator+= (const \fBVec3\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line 141 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP& \fBVec3\fP< T >::operator\-= (const \fBVec3\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line 149 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP& \fBVec3\fP< T >::operator= (\fBVec3\fP< T > &&)\fC [default]\fP"

.SS "template<class T> \fBVec3\fP& \fBVec3\fP< T >::operator= (const \fBVec3\fP< T > & v)\fC [inline]\fP"

.PP
Definition at line 134 of file vec3\&.h\&.
.SS "template<class T> void \fBVec3\fP< T >::print () const\fC [inline]\fP"

.PP
Definition at line 167 of file vec3\&.h\&.
.SS "template<class T> void \fBVec3\fP< T >::set_Values (T x, T y, T z)\fC [inline]\fP"

.PP
Definition at line 41 of file vec3\&.h\&.
.SS "template<class T> void \fBVec3\fP< T >::setX (T x)\fC [inline]\fP"

.PP
Definition at line 37 of file vec3\&.h\&.
.SS "template<class T> void \fBVec3\fP< T >::setY (T y)\fC [inline]\fP"

.PP
Definition at line 38 of file vec3\&.h\&.
.SS "template<class T> void \fBVec3\fP< T >::setZ (T z)\fC [inline]\fP"

.PP
Definition at line 39 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP \fBVec3\fP< T >::sub_EW (float num)\fC [inline]\fP"

.PP
Definition at line 88 of file vec3\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec3\fP \fBVec3\fP< T >::sub_EW (\fBVec3\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 98 of file vec3\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T> \fBVec3\fP operator+ (\fBVec3\fP< T > lhs, const \fBVec3\fP< T > & rhs)\fC [friend]\fP"

.PP
Definition at line 157 of file vec3\&.h\&.
.SS "template<class T> \fBVec3\fP operator\- (\fBVec3\fP< T > lhs, const \fBVec3\fP< T > & rhs)\fC [friend]\fP"

.PP
Definition at line 162 of file vec3\&.h\&.
.SS "template<class T> void swap (\fBVec3\fP< T > & first, \fBVec3\fP< T > & second)\fC [friend]\fP"

.PP
Definition at line 174 of file vec3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> T \fBVec3\fP< T >::x_\fC [private]\fP"

.PP
Definition at line 172 of file vec3\&.h\&.
.SS "template<class T> T \fBVec3\fP< T >::y_\fC [private]\fP"

.PP
Definition at line 172 of file vec3\&.h\&.
.SS "template<class T> T \fBVec3\fP< T >::z_\fC [private]\fP"

.PP
Definition at line 172 of file vec3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
