.TH "Vec4< T >" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec4< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vec4\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec4\fP ()"
.br
.ti -1c
.RI "\fBVec4\fP (T x, T y, T z, T w)"
.br
.ti -1c
.RI "\fBVec4\fP (\fBVec4\fP &&)=default"
.br
.ti -1c
.RI "\fBVec4\fP & \fBoperator=\fP (\fBVec4\fP &&)=default"
.br
.ti -1c
.RI "\fB~Vec4\fP ()"
.br
.ti -1c
.RI "T \fBgetX\fP () const"
.br
.ti -1c
.RI "T \fBgetY\fP () const"
.br
.ti -1c
.RI "T \fBgetZ\fP () const"
.br
.ti -1c
.RI "T \fBgetW\fP () const"
.br
.ti -1c
.RI "void \fBsetX\fP (T x)"
.br
.ti -1c
.RI "void \fBsetY\fP (T y)"
.br
.ti -1c
.RI "void \fBsetZ\fP (T z)"
.br
.ti -1c
.RI "void \fBsetW\fP (T w)"
.br
.ti -1c
.RI "void \fBset_Values\fP (T x, T y, T z, T w)"
.br
.ti -1c
.RI "\fBVec4\fP \fBmult_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec4\fP \fBmult_EW\fP (\fBVec4\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec4\fP \fBadd_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec4\fP \fBadd_EW\fP (\fBVec4\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec4\fP \fBsub_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec4\fP \fBsub_EW\fP (\fBVec4\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec4\fP \fBdiv_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec4\fP \fBdiv_EW\fP (\fBVec4\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec4\fP (const \fBVec4\fP &v)"
.br
.ti -1c
.RI "\fBVec4\fP & \fBoperator=\fP (const \fBVec4\fP &v)"
.br
.ti -1c
.RI "\fBVec4\fP & \fBoperator+=\fP (const \fBVec4\fP &rhs)"
.br
.ti -1c
.RI "\fBVec4\fP & \fBoperator\-=\fP (const \fBVec4\fP &rhs)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBx_\fP"
.br
.ti -1c
.RI "T \fBy_\fP"
.br
.ti -1c
.RI "T \fBz_\fP"
.br
.ti -1c
.RI "T \fBw_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBVec4\fP \fBoperator+\fP (\fBVec4\fP lhs, const \fBVec4\fP &rhs)"
.br
.ti -1c
.RI "\fBVec4\fP \fBoperator\-\fP (\fBVec4\fP lhs, const \fBVec4\fP &rhs)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBVec4\fP &first, \fBVec4\fP &second)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class Vec4< T >"

.PP
Definition at line 15 of file vec4\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBVec4\fP< T >::\fBVec4\fP ()\fC [inline]\fP"

.PP
Definition at line 18 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP< T >::\fBVec4\fP (T x, T y, T z, T w)\fC [inline]\fP"

.PP
Definition at line 19 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP< T >::\fBVec4\fP (\fBVec4\fP< T > &&)\fC [default]\fP"

.SS "template<class T> \fBVec4\fP< T >::~\fBVec4\fP ()\fC [inline]\fP"

.PP
Definition at line 23 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP< T >::\fBVec4\fP (const \fBVec4\fP< T > & v)\fC [inline]\fP"

.PP
Definition at line 130 of file vec4\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T> \fBVec4\fP \fBVec4\fP< T >::add_EW (float num)\fC [inline]\fP"

.PP
Definition at line 64 of file vec4\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec4\fP \fBVec4\fP< T >::add_EW (\fBVec4\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 75 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP \fBVec4\fP< T >::div_EW (float num)\fC [inline]\fP"

.PP
Definition at line 108 of file vec4\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec4\fP \fBVec4\fP< T >::div_EW (\fBVec4\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 119 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::getW () const\fC [inline]\fP"

.PP
Definition at line 28 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::getX () const\fC [inline]\fP"

.PP
Definition at line 25 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::getY () const\fC [inline]\fP"

.PP
Definition at line 26 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::getZ () const\fC [inline]\fP"

.PP
Definition at line 27 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP \fBVec4\fP< T >::mult_EW (float num)\fC [inline]\fP"

.PP
Definition at line 42 of file vec4\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec4\fP \fBVec4\fP< T >::mult_EW (\fBVec4\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 53 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP& \fBVec4\fP< T >::operator+= (const \fBVec4\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line 144 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP& \fBVec4\fP< T >::operator\-= (const \fBVec4\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line 153 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP& \fBVec4\fP< T >::operator= (\fBVec4\fP< T > &&)\fC [default]\fP"

.SS "template<class T> \fBVec4\fP& \fBVec4\fP< T >::operator= (const \fBVec4\fP< T > & v)\fC [inline]\fP"

.PP
Definition at line 137 of file vec4\&.h\&.
.SS "template<class T> void \fBVec4\fP< T >::print () const\fC [inline]\fP"

.PP
Definition at line 172 of file vec4\&.h\&.
.SS "template<class T> void \fBVec4\fP< T >::set_Values (T x, T y, T z, T w)\fC [inline]\fP"

.PP
Definition at line 34 of file vec4\&.h\&.
.SS "template<class T> void \fBVec4\fP< T >::setW (T w)\fC [inline]\fP"

.PP
Definition at line 32 of file vec4\&.h\&.
.SS "template<class T> void \fBVec4\fP< T >::setX (T x)\fC [inline]\fP"

.PP
Definition at line 29 of file vec4\&.h\&.
.SS "template<class T> void \fBVec4\fP< T >::setY (T y)\fC [inline]\fP"

.PP
Definition at line 30 of file vec4\&.h\&.
.SS "template<class T> void \fBVec4\fP< T >::setZ (T z)\fC [inline]\fP"

.PP
Definition at line 31 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP \fBVec4\fP< T >::sub_EW (float num)\fC [inline]\fP"

.PP
Definition at line 86 of file vec4\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec4\fP \fBVec4\fP< T >::sub_EW (\fBVec4\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 97 of file vec4\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T> \fBVec4\fP operator+ (\fBVec4\fP< T > lhs, const \fBVec4\fP< T > & rhs)\fC [friend]\fP"

.PP
Definition at line 162 of file vec4\&.h\&.
.SS "template<class T> \fBVec4\fP operator\- (\fBVec4\fP< T > lhs, const \fBVec4\fP< T > & rhs)\fC [friend]\fP"

.PP
Definition at line 167 of file vec4\&.h\&.
.SS "template<class T> void swap (\fBVec4\fP< T > & first, \fBVec4\fP< T > & second)\fC [friend]\fP"

.PP
Definition at line 179 of file vec4\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> T \fBVec4\fP< T >::w_\fC [private]\fP"

.PP
Definition at line 177 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::x_\fC [private]\fP"

.PP
Definition at line 177 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::y_\fC [private]\fP"

.PP
Definition at line 177 of file vec4\&.h\&.
.SS "template<class T> T \fBVec4\fP< T >::z_\fC [private]\fP"

.PP
Definition at line 177 of file vec4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
