.TH "Inc/devs/a4988.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/a4988.h
.SH SYNOPSIS
.br
.PP
\fC#include 'periphs/tim\&.h'\fP
.br
\fC#include 'periphs/gpio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBA4988\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBA4988_setDirection\fP (\fBA4988\fP *stepper, uint32_t dir)"
.br
.ti -1c
.RI "void \fBA4988_toggleDirection\fP (\fBA4988\fP *stepper)"
.br
.ti -1c
.RI "void \fBA4988_step\fP (\fBA4988\fP *stepper)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void A4988_setDirection (\fBA4988\fP * stepper, uint32_t dir)"

.SS "void A4988_step (\fBA4988\fP * stepper)"

.SS "void A4988_toggleDirection (\fBA4988\fP * stepper)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
