.TH "Angle_PID" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Angle_PID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pid_algorithms\&.h>\fP
.PP
Inherits \fBPID_Algorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAngle_PID\fP (float p, float i, float d)"
.br
.ti -1c
.RI "\fBAngle_PID\fP ()"
.br
.ti -1c
.RI "\fBAngle_PID\fP (\fBAngle_PID\fP &&)=default"
.br
.ti -1c
.RI "\fBAngle_PID\fP (const \fBAngle_PID\fP &)=default"
.br
.ti -1c
.RI "\fBAngle_PID\fP & \fBoperator=\fP (\fBAngle_PID\fP &&)=default"
.br
.ti -1c
.RI "\fBAngle_PID\fP & \fBoperator=\fP (const \fBAngle_PID\fP &)=default"
.br
.ti -1c
.RI "\fB~Angle_PID\fP ()"
.br
.ti -1c
.RI "float \fBcompute\fP (float error, uint32_t dt_millis)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBl_output_\fP"
.br
.ti -1c
.RI "float \fBerr_sum_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 193 of file pid_algorithms\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Angle_PID::Angle_PID (float p, float i, float d)\fC [inline]\fP"

.PP
Definition at line 196 of file pid_algorithms\&.h\&.
.SS "Angle_PID::Angle_PID ()\fC [inline]\fP"

.PP
Definition at line 202 of file pid_algorithms\&.h\&.
.SS "Angle_PID::Angle_PID (\fBAngle_PID\fP &&)\fC [default]\fP"

.SS "Angle_PID::Angle_PID (const \fBAngle_PID\fP &)\fC [default]\fP"

.SS "Angle_PID::~Angle_PID ()\fC [inline]\fP"

.PP
Definition at line 212 of file pid_algorithms\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "float Angle_PID::compute (float error, uint32_t dt_millis)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPID_Algorithm\fP\&.
.PP
Definition at line 222 of file pid_algorithms\&.h\&.
.SS "\fBAngle_PID\fP& Angle_PID::operator= (\fBAngle_PID\fP &&)\fC [default]\fP"

.SS "\fBAngle_PID\fP& Angle_PID::operator= (const \fBAngle_PID\fP &)\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float Angle_PID::err_sum_\fC [private]\fP"

.PP
Definition at line 258 of file pid_algorithms\&.h\&.
.SS "float Angle_PID::l_output_\fC [private]\fP"

.PP
Definition at line 257 of file pid_algorithms\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
