.TH "Inc/periphs Directory Reference" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/periphs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadc\&.h\fP"
.br
.ti -1c
.RI "file \fBgpio\&.h\fP"
.br
.ti -1c
.RI "file \fBi2c\&.h\fP"
.br
.ti -1c
.RI "file \fBtim\&.h\fP"
.br
.ti -1c
.RI "file \fBusart\&.h\fP"
.br
.in -1c
