.TH "Src Directory Reference" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdevs\fP"
.br
.ti -1c
.RI "directory \fBperiphs\fP"
.br
.ti -1c
.RI "directory \fBrobot\fP"
.br
.ti -1c
.RI "directory \fBsys\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
