.TH "Src/robot Directory Reference" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/robot Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrobo_init\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrobo_orientation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrobot\&.cpp\fP"
.br
.in -1c
