.TH "Inc/utils/defines.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/utils/defines.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   (3\&.1415926535897932384626433832795)"
.br
.ti -1c
.RI "#define \fBSAMPLE_TIME\fP   (10)"
.br
.ti -1c
.RI "#define \fBLEG_MOTOR_MAX_OMEGA\fP   (70)"
.br
.ti -1c
.RI "#define \fBSTEERING_MOTOR_MAX_OMEGA\fP   (7)"
.br
.ti -1c
.RI "#define \fBLEG_TO_MOTOR_RATIO\fP   (4)"
.br
.ti -1c
.RI "#define \fBMOTOR_TO_ENCODER_RATIO\fP   (1)"
.br
.ti -1c
.RI "#define \fBLEG_TO_ENCODER_RATIO\fP   (\fBLEG_TO_MOTOR_RATIO\fP * \fBMOTOR_TO_ENCODER_RATIO\fP)"
.br
.ti -1c
.RI "#define \fBBEARING_TO_STEERING_RATIO\fP   (8)"
.br
.ti -1c
.RI "#define \fBBODY_WEIGHT\fP   (8)"
.br
.ti -1c
.RI "#define \fBLEG_WEIGHT\fP   (1)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BEARING_TO_STEERING_RATIO   (8)"

.PP
Definition at line 11 of file defines\&.h\&.
.SS "#define BODY_WEIGHT   (8)"

.PP
Definition at line 12 of file defines\&.h\&.
.SS "#define LEG_MOTOR_MAX_OMEGA   (70)"

.PP
Definition at line 6 of file defines\&.h\&.
.SS "#define LEG_TO_ENCODER_RATIO   (\fBLEG_TO_MOTOR_RATIO\fP * \fBMOTOR_TO_ENCODER_RATIO\fP)"

.PP
Definition at line 10 of file defines\&.h\&.
.SS "#define LEG_TO_MOTOR_RATIO   (4)"

.PP
Definition at line 8 of file defines\&.h\&.
.SS "#define LEG_WEIGHT   (1)"

.PP
Definition at line 13 of file defines\&.h\&.
.SS "#define MOTOR_TO_ENCODER_RATIO   (1)"

.PP
Definition at line 9 of file defines\&.h\&.
.SS "#define PI   (3\&.1415926535897932384626433832795)"

.PP
Definition at line 4 of file defines\&.h\&.
.SS "#define SAMPLE_TIME   (10)"

.PP
Definition at line 5 of file defines\&.h\&.
.SS "#define STEERING_MOTOR_MAX_OMEGA   (7)"

.PP
Definition at line 7 of file defines\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
