.TH "Inc/devs/encoder.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/encoder.h
.SH SYNOPSIS
.br
.PP
\fC#include 'defines\&.h'\fP
.br
\fC#include 'stm32f4xx_hal\&.h'\fP
.br
\fC#include 'tim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBencoder_config\fP"
.br
.ti -1c
.RI "class \fBencoder\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
