.TH "encoder" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encoder\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBencoder\fP ()"
.br
.ti -1c
.RI "\fBencoder\fP (\fBencoder_config\fP *\fBencoder\fP)"
.br
.ti -1c
.RI "\fBencoder\fP (\fBencoder\fP &&)=default"
.br
.ti -1c
.RI "\fBencoder\fP (const \fBencoder\fP &)=default"
.br
.ti -1c
.RI "\fBencoder\fP & \fBoperator=\fP (\fBencoder\fP &&)=default"
.br
.ti -1c
.RI "\fBencoder\fP & \fBoperator=\fP (const \fBencoder\fP &)=default"
.br
.ti -1c
.RI "\fB~encoder\fP ()"
.br
.ti -1c
.RI "void \fBset_config\fP (\fBencoder_config\fP *\fBencoder\fP)"
.br
.ti -1c
.RI "float \fBget_omega\fP (void)"
.br
.ti -1c
.RI "void \fBcalculate_omega\fP (void)"
.br
.ti -1c
.RI "float \fBget_angle\fP (void)"
.br
.ti -1c
.RI "float \fBget_actual_angle\fP (void)"
.br
.ti -1c
.RI "void \fBreset_angle\fP (float)"
.br
.ti -1c
.RI "int32_t \fBget_count\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBencoder_config\fP * \fBencoder_\fP"
.br
.ti -1c
.RI "int32_t \fBcount_\fP = 0"
.br
.ti -1c
.RI "float \fBomega_\fP = 0"
.br
.ti -1c
.RI "float \fBangle_\fP = 0"
.br
.ti -1c
.RI "float \fBactual_angle_\fP = 0"
.br
.ti -1c
.RI "int32_t \fBactual_count_\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file encoder\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "encoder::encoder ()\fC [inline]\fP"

.PP
Definition at line 18 of file encoder\&.h\&.
.SS "encoder::encoder (\fBencoder_config\fP * encoder)\fC [inline]\fP"

.PP
Definition at line 19 of file encoder\&.h\&.
.SS "encoder::encoder (\fBencoder\fP &&)\fC [default]\fP"

.SS "encoder::encoder (const \fBencoder\fP &)\fC [default]\fP"

.SS "encoder::~encoder ()\fC [inline]\fP"

.PP
Definition at line 24 of file encoder\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void encoder::calculate_omega (void)"

.PP
Definition at line 3 of file encoder\&.cpp\&.
.SS "float encoder::get_actual_angle (void)"

.PP
Definition at line 26 of file encoder\&.cpp\&.
.SS "float encoder::get_angle (void)"

.PP
Definition at line 14 of file encoder\&.cpp\&.
.SS "int32_t encoder::get_count ()"

.PP
Definition at line 38 of file encoder\&.cpp\&.
.SS "float encoder::get_omega (void)"

.PP
Definition at line 10 of file encoder\&.cpp\&.
.SS "\fBencoder\fP& encoder::operator= (\fBencoder\fP &&)\fC [default]\fP"

.SS "\fBencoder\fP& encoder::operator= (const \fBencoder\fP &)\fC [default]\fP"

.SS "void encoder::reset_angle (float angle_in_radian)"

.PP
Definition at line 31 of file encoder\&.cpp\&.
.SS "void encoder::set_config (\fBencoder_config\fP * encoder)\fC [inline]\fP"

.PP
Definition at line 25 of file encoder\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float encoder::actual_angle_ = 0\fC [private]\fP"

.PP
Definition at line 39 of file encoder\&.h\&.
.SS "int32_t encoder::actual_count_ = 0\fC [private]\fP"

.PP
Definition at line 40 of file encoder\&.h\&.
.SS "float encoder::angle_ = 0\fC [private]\fP"

.PP
Definition at line 38 of file encoder\&.h\&.
.SS "int32_t encoder::count_ = 0\fC [private]\fP"

.PP
Definition at line 36 of file encoder\&.h\&.
.SS "\fBencoder_config\fP* encoder::encoder_\fC [private]\fP"

.PP
Definition at line 35 of file encoder\&.h\&.
.SS "float encoder::omega_ = 0\fC [private]\fP"

.PP
Definition at line 37 of file encoder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
