.TH "encoder_config" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder_config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encoder\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TIM_HandleTypeDef * \fBhenc\fP"
.br
.ti -1c
.RI "uint16_t \fBppr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file encoder\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "TIM_HandleTypeDef* encoder_config::henc"

.PP
Definition at line 11 of file encoder\&.h\&.
.SS "uint16_t encoder_config::ppr"

.PP
Definition at line 12 of file encoder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
