.TH "FilteredDiscrete_PID" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilteredDiscrete_PID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pid_algorithms\&.h>\fP
.PP
Inherits \fBPID_Algorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilteredDiscrete_PID\fP (float p, float i, float d, float N=0)"
.br
.ti -1c
.RI "\fBFilteredDiscrete_PID\fP ()"
.br
.ti -1c
.RI "\fBFilteredDiscrete_PID\fP (\fBFilteredDiscrete_PID\fP &&)=default"
.br
.ti -1c
.RI "\fBFilteredDiscrete_PID\fP (const \fBFilteredDiscrete_PID\fP &)=default"
.br
.ti -1c
.RI "\fBFilteredDiscrete_PID\fP & \fBoperator=\fP (\fBFilteredDiscrete_PID\fP &&)=default"
.br
.ti -1c
.RI "\fBFilteredDiscrete_PID\fP & \fBoperator=\fP (const \fBFilteredDiscrete_PID\fP &)=default"
.br
.ti -1c
.RI "\fB~FilteredDiscrete_PID\fP ()"
.br
.ti -1c
.RI "void \fBset_N\fP (float N)"
.br
.ti -1c
.RI "float \fBcompute\fP (float error, uint32_t dt_millis)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBN_\fP"
.br
.ti -1c
.RI "float \fBl_output_\fP"
.br
.ti -1c
.RI "float \fBll_output_\fP"
.br
.ti -1c
.RI "float \fBl_err_\fP"
.br
.ti -1c
.RI "float \fBll_err_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 110 of file pid_algorithms\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FilteredDiscrete_PID::FilteredDiscrete_PID (float p, float i, float d, float N = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 113 of file pid_algorithms\&.h\&.
.SS "FilteredDiscrete_PID::FilteredDiscrete_PID ()\fC [inline]\fP"

.PP
Definition at line 120 of file pid_algorithms\&.h\&.
.SS "FilteredDiscrete_PID::FilteredDiscrete_PID (\fBFilteredDiscrete_PID\fP &&)\fC [default]\fP"

.SS "FilteredDiscrete_PID::FilteredDiscrete_PID (const \fBFilteredDiscrete_PID\fP &)\fC [default]\fP"

.SS "FilteredDiscrete_PID::~FilteredDiscrete_PID ()\fC [inline]\fP"

.PP
Definition at line 131 of file pid_algorithms\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "float FilteredDiscrete_PID::compute (float error, uint32_t dt_millis)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPID_Algorithm\fP\&.
.PP
Definition at line 150 of file pid_algorithms\&.h\&.
.SS "\fBFilteredDiscrete_PID\fP& FilteredDiscrete_PID::operator= (\fBFilteredDiscrete_PID\fP &&)\fC [default]\fP"

.SS "\fBFilteredDiscrete_PID\fP& FilteredDiscrete_PID::operator= (const \fBFilteredDiscrete_PID\fP &)\fC [default]\fP"

.SS "void FilteredDiscrete_PID::set_N (float N)\fC [inline]\fP"

.PP
Definition at line 133 of file pid_algorithms\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float FilteredDiscrete_PID::l_err_\fC [private]\fP"

.PP
Definition at line 189 of file pid_algorithms\&.h\&.
.SS "float FilteredDiscrete_PID::l_output_\fC [private]\fP"

.PP
Definition at line 187 of file pid_algorithms\&.h\&.
.SS "float FilteredDiscrete_PID::ll_err_\fC [private]\fP"

.PP
Definition at line 190 of file pid_algorithms\&.h\&.
.SS "float FilteredDiscrete_PID::ll_output_\fC [private]\fP"

.PP
Definition at line 188 of file pid_algorithms\&.h\&.
.SS "float FilteredDiscrete_PID::N_\fC [private]\fP"

.PP
Definition at line 185 of file pid_algorithms\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
