.TH "Src/devs/interrupt.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/devs/interrupt.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'robo_init\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_GPIO_EXTI_Callback\fP (uint16_t GPIO_Pin)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBleg\fP \fBleg\fP [2]"
.br
.ti -1c
.RI "bool \fBsand_dune_crossed_flag\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)"

.PP
Definition at line 7 of file interrupt\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBleg\fP \fBleg\fP[2]"

.PP
Definition at line 3 of file robo_init\&.cpp\&.
.SS "bool sand_dune_crossed_flag"

.PP
Definition at line 17 of file robot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
