.TH "Src/devs/leg.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/devs/leg.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'leg\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static float \fBramped_value\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "float ramped_value = 0\fC [static]\fP"

.PP
Definition at line 2 of file leg\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
