.TH "Mat" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMat\fP ()"
.br
.ti -1c
.RI "template<size_t M, size_t N> \fBMat\fP (const float(&mat)[M][N])"
.br
.ti -1c
.RI "\fBMat\fP (uint8_t \fBrows\fP, uint8_t columns)"
.br
.ti -1c
.RI "\fBMat\fP (\fBMat\fP &&)=default"
.br
.ti -1c
.RI "\fBMat\fP & \fBoperator=\fP (\fBMat\fP &&)=default"
.br
.ti -1c
.RI "\fB~Mat\fP ()"
.br
.ti -1c
.RI "uint8_t \fBrows\fP () const"
.br
.ti -1c
.RI "uint8_t \fBcols\fP () const"
.br
.ti -1c
.RI "float & \fBat\fP (uint8_t i, uint8_t j)"
.br
.ti -1c
.RI "\fBMat\fP (const \fBMat\fP &m)"
.br
.ti -1c
.RI "\fBMat\fP & \fBoperator=\fP (const \fBMat\fP &m)"
.br
.ti -1c
.RI "\fBMat\fP & \fBoperator+=\fP (const \fBMat\fP &rhs)"
.br
.ti -1c
.RI "\fBMat\fP & \fBoperator\-=\fP (const \fBMat\fP &rhs)"
.br
.ti -1c
.RI "\fBMat\fP & \fBoperator *=\fP (const \fBMat\fP &rhs)"
.br
.ti -1c
.RI "\fBMat\fP & \fBoperator *=\fP (const \fBVec3\fP< float > &rhs)"
.br
.ti -1c
.RI "\fBMat\fP \fBmult\fP (const \fBMat\fP &m)"
.br
.ti -1c
.RI "\fBMat\fP \fBmult_EW\fP (float num)"
.br
.ti -1c
.RI "\fBMat\fP \fBtranspose\fP ()"
.br
.ti -1c
.RI "\fBMat\fP \fBtrans\fP ()"
.br
.ti -1c
.RI "void \fBfill\fP (float num)"
.br
.ti -1c
.RI "template<size_t M, size_t N> void \fBfill\fP (const float(&mat)[M][N])"
.br
.ti -1c
.RI "void \fBadd_Rows\fP (uint8_t r)"
.br
.ti -1c
.RI "void \fBadd_Cols\fP (uint8_t c)"
.br
.ti -1c
.RI "bool \fBis_Zero\fP () const"
.br
.ti -1c
.RI "void \fBswap_Rows\fP (uint8_t a, uint8_t b)"
.br
.ti -1c
.RI "void \fBswap_Cols\fP (size_t a, size_t b)"
.br
.ti -1c
.RI "bool \fBinv\fP (\fBMat\fP &inv) const"
.br
.ti -1c
.RI "\fBMat\fP \fBinv\fP () const"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMat\fP \fBeye\fP (uint8_t n)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBmatrix_\fP [\fBMAX_MATRIX_ROWS\fP][\fBMAX_MATRIX_COLS\fP]"
.br
.ti -1c
.RI "uint8_t \fBrows_\fP"
.br
.ti -1c
.RI "uint8_t \fBcols_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBMat\fP \fBoperator+\fP (\fBMat\fP lhs, const \fBMat\fP &rhs)"
.br
.ti -1c
.RI "\fBMat\fP \fBoperator\-\fP (\fBMat\fP lhs, const \fBMat\fP &rhs)"
.br
.ti -1c
.RI "\fBMat\fP \fBoperator *\fP (\fBMat\fP lhs, const \fBMat\fP &rhs)"
.br
.ti -1c
.RI "\fBMat\fP \fBoperator *\fP (\fBMat\fP lhs, const \fBVec3\fP< float > &rhs)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBMat\fP &first, \fBMat\fP &second)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file mat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mat::Mat ()\fC [inline]\fP"

.PP
Definition at line 21 of file mat\&.h\&.
.SS "template<size_t M, size_t N> Mat::Mat (const float(&) mat[M][N])\fC [inline]\fP"

.PP
Definition at line 24 of file mat\&.h\&.
.SS "Mat::Mat (uint8_t rows, uint8_t columns)"

.PP
Definition at line 12 of file mat\&.cpp\&.
.SS "Mat::Mat (\fBMat\fP &&)\fC [default]\fP"

.SS "Mat::~Mat ()\fC [inline]\fP"

.PP
Definition at line 31 of file mat\&.h\&.
.SS "Mat::Mat (const \fBMat\fP & m)"

.PP
Definition at line 27 of file mat\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Mat::add_Cols (uint8_t c)\fC [inline]\fP"

.PP
Definition at line 111 of file mat\&.h\&.
.SS "void Mat::add_Rows (uint8_t r)\fC [inline]\fP"

.PP
Definition at line 105 of file mat\&.h\&.
.SS "float& Mat::at (uint8_t i, uint8_t j)\fC [inline]\fP"

.PP
Definition at line 36 of file mat\&.h\&.
.SS "uint8_t Mat::cols () const\fC [inline]\fP"

.PP
Definition at line 34 of file mat\&.h\&.
.SS "\fBMat\fP Mat::eye (uint8_t n)\fC [static]\fP"

.PP
Definition at line 140 of file mat\&.cpp\&.
.SS "void Mat::fill (float num)\fC [inline]\fP"

.PP
Definition at line 85 of file mat\&.h\&.
.SS "template<size_t M, size_t N> void Mat::fill (const float(&) mat[M][N])\fC [inline]\fP"

.PP
Definition at line 94 of file mat\&.h\&.
.SS "bool Mat::inv (\fBMat\fP & inv) const"
inverse based on LU factorization with partial pivotting 
.PP
Definition at line 197 of file mat\&.cpp\&.
.SS "\fBMat\fP Mat::inv () const\fC [inline]\fP"

.PP
Definition at line 124 of file mat\&.h\&.
.SS "bool Mat::is_Zero () const"

.PP
Definition at line 150 of file mat\&.cpp\&.
.SS "\fBMat\fP Mat::mult (const \fBMat\fP & m)"

.PP
Definition at line 96 of file mat\&.cpp\&.
.SS "\fBMat\fP Mat::mult_EW (float num)"

.PP
Definition at line 117 of file mat\&.cpp\&.
.SS "\fBMat\fP & Mat::operator *= (const \fBMat\fP & rhs)"

.PP
Definition at line 79 of file mat\&.cpp\&.
.SS "\fBMat\fP & Mat::operator *= (const \fBVec3\fP< float > & rhs)"

.PP
Definition at line 85 of file mat\&.cpp\&.
.SS "\fBMat\fP & Mat::operator+= (const \fBMat\fP & rhs)"

.PP
Definition at line 49 of file mat\&.cpp\&.
.SS "\fBMat\fP & Mat::operator\-= (const \fBMat\fP & rhs)"

.PP
Definition at line 64 of file mat\&.cpp\&.
.SS "\fBMat\fP& Mat::operator= (\fBMat\fP &&)\fC [default]\fP"

.SS "\fBMat\fP& Mat::operator= (const \fBMat\fP & m)\fC [inline]\fP"

.PP
Definition at line 46 of file mat\&.h\&.
.SS "void Mat::print () const\fC [inline]\fP"

.PP
Definition at line 135 of file mat\&.h\&.
.SS "uint8_t Mat::rows () const\fC [inline]\fP"

.PP
Definition at line 33 of file mat\&.h\&.
.SS "void Mat::swap_Cols (size_t a, size_t b)"

.PP
Definition at line 178 of file mat\&.cpp\&.
.SS "void Mat::swap_Rows (uint8_t a, uint8_t b)"

.PP
Definition at line 162 of file mat\&.cpp\&.
.SS "\fBMat\fP Mat::trans ()\fC [inline]\fP"

.PP
Definition at line 83 of file mat\&.h\&.
.SS "\fBMat\fP Mat::transpose ()"

.PP
Definition at line 129 of file mat\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBMat\fP operator * (\fBMat\fP lhs, const \fBMat\fP & rhs)\fC [friend]\fP"

.PP
Definition at line 68 of file mat\&.h\&.
.SS "\fBMat\fP operator * (\fBMat\fP lhs, const \fBVec3\fP< float > & rhs)\fC [friend]\fP"

.PP
Definition at line 73 of file mat\&.h\&.
.SS "\fBMat\fP operator+ (\fBMat\fP lhs, const \fBMat\fP & rhs)\fC [friend]\fP"

.PP
Definition at line 58 of file mat\&.h\&.
.SS "\fBMat\fP operator\- (\fBMat\fP lhs, const \fBMat\fP & rhs)\fC [friend]\fP"

.PP
Definition at line 63 of file mat\&.h\&.
.SS "void swap (\fBMat\fP & first, \fBMat\fP & second)\fC [friend]\fP"

.PP
Definition at line 38 of file mat\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t Mat::cols_\fC [private]\fP"

.PP
Definition at line 146 of file mat\&.h\&.
.SS "float Mat::matrix_[\fBMAX_MATRIX_ROWS\fP][\fBMAX_MATRIX_COLS\fP]\fC [private]\fP"

.PP
Definition at line 145 of file mat\&.h\&.
.SS "uint8_t Mat::rows_\fC [private]\fP"

.PP
Definition at line 146 of file mat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
