.TH "Src/devs/motor.cpp" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/devs/motor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'motor\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static uint16_t \fBtime_period\fP (uint16_t PWM_frequency)"
.br
.ti -1c
.RI "static void \fBset_DutyCycle_Primary\fP (TIM_HandleTypeDef *htim, uint32_t Channel, uint16_t dutyCycle)"
.br
.ti -1c
.RI "static void \fBset_DutyCycle\fP (\fBmotor_config\fP *m, uint16_t dutyCycle)"
.br
.ti -1c
.RI "static void \fBset_motorDirection\fP (\fBmotor_config\fP *m, \fBDirection\fP d)"
.br
.ti -1c
.RI "static void \fBset_motorOmega\fP (\fBmotor_config\fP *m, float omega)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void set_DutyCycle (\fBmotor_config\fP * m, uint16_t dutyCycle)\fC [static]\fP"

.PP
Definition at line 19 of file motor\&.cpp\&.
.SS "static void set_DutyCycle_Primary (TIM_HandleTypeDef * htim, uint32_t Channel, uint16_t dutyCycle)\fC [static]\fP"

.PP
Definition at line 12 of file motor\&.cpp\&.
.SS "static void set_motorDirection (\fBmotor_config\fP * m, \fBDirection\fP d)\fC [static]\fP"

.PP
Definition at line 24 of file motor\&.cpp\&.
.SS "static void set_motorOmega (\fBmotor_config\fP * m, float omega)\fC [static]\fP"

.PP
Definition at line 43 of file motor\&.cpp\&.
.SS "static uint16_t time_period (uint16_t PWM_frequency)\fC [static]\fP"

.PP
Definition at line 3 of file motor\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
