.TH "motor" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <motor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmotor\fP ()"
.br
.ti -1c
.RI "\fBmotor\fP (\fBmotor_config\fP *\fBmotor\fP)"
.br
.ti -1c
.RI "\fBmotor\fP (\fBmotor\fP &&)=default"
.br
.ti -1c
.RI "\fBmotor\fP (const \fBmotor\fP &)=default"
.br
.ti -1c
.RI "\fBmotor\fP & \fBoperator=\fP (\fBmotor\fP &&)=default"
.br
.ti -1c
.RI "\fBmotor\fP & \fBoperator=\fP (const \fBmotor\fP &)=default"
.br
.ti -1c
.RI "\fB~motor\fP ()"
.br
.ti -1c
.RI "void \fBset_config\fP (\fBmotor_config\fP *\fBmotor\fP)"
.br
.ti -1c
.RI "float \fBget_max_omega\fP ()"
.br
.ti -1c
.RI "void \fBset_direction\fP (enum \fBDirection\fP dir)"
.br
.ti -1c
.RI "void \fBset_omega\fP (float omega)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBmotor_config\fP * \fBmotor_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file motor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "motor::motor ()\fC [inline]\fP"

.PP
Definition at line 29 of file motor\&.h\&.
.SS "motor::motor (\fBmotor_config\fP * motor)\fC [inline]\fP"

.PP
Definition at line 30 of file motor\&.h\&.
.SS "motor::motor (\fBmotor\fP &&)\fC [default]\fP"

.SS "motor::motor (const \fBmotor\fP &)\fC [default]\fP"

.SS "motor::~motor ()\fC [inline]\fP"

.PP
Definition at line 35 of file motor\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "float motor::get_max_omega ()\fC [inline]\fP"

.PP
Definition at line 37 of file motor\&.h\&.
.SS "\fBmotor\fP& motor::operator= (\fBmotor\fP &&)\fC [default]\fP"

.SS "\fBmotor\fP& motor::operator= (const \fBmotor\fP &)\fC [default]\fP"

.SS "void motor::set_config (\fBmotor_config\fP * motor)\fC [inline]\fP"

.PP
Definition at line 36 of file motor\&.h\&.
.SS "void motor::set_direction (enum \fBDirection\fP dir)"

.SS "void motor::set_omega (float omega)"

.PP
Definition at line 49 of file motor\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmotor_config\fP* motor::motor_\fC [private]\fP"

.PP
Definition at line 41 of file motor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
