.TH "Inc/devs/mpu6050_reg.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/mpu6050_reg.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBXG_OFFS_TC\fP   0x00"
.br
.ti -1c
.RI "#define \fBYG_OFFS_TC\fP   0x01"
.br
.ti -1c
.RI "#define \fBZG_OFFS_TC\fP   0x02"
.br
.ti -1c
.RI "#define \fBX_FINE_GAIN\fP   0x03"
.br
.ti -1c
.RI "#define \fBY_FINE_GAIN\fP   0x04"
.br
.ti -1c
.RI "#define \fBZ_FINE_GAIN\fP   0x05"
.br
.ti -1c
.RI "#define \fBXA_OFFS_H\fP   0x06"
.br
.ti -1c
.RI "#define \fBXA_OFFS_L_TC\fP   0x07"
.br
.ti -1c
.RI "#define \fBYA_OFFS_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBYA_OFFS_L_TC\fP   0x09"
.br
.ti -1c
.RI "#define \fBZA_OFFS_H\fP   0x0A"
.br
.ti -1c
.RI "#define \fBZA_OFFS_L_TC\fP   0x0B"
.br
.ti -1c
.RI "#define \fBXG_OFFS_USRH\fP   0x13"
.br
.ti -1c
.RI "#define \fBXG_OFFS_USRL\fP   0x14"
.br
.ti -1c
.RI "#define \fBYG_OFFS_USRH\fP   0x15"
.br
.ti -1c
.RI "#define \fBYG_OFFS_USRL\fP   0x16"
.br
.ti -1c
.RI "#define \fBZG_OFFS_USRH\fP   0x17"
.br
.ti -1c
.RI "#define \fBZG_OFFS_USRL\fP   0x18"
.br
.ti -1c
.RI "#define \fBSMPLRT_DIV\fP   0x19"
.br
.ti -1c
.RI "#define \fBCONFIG\fP   0x1A"
.br
.ti -1c
.RI "#define \fBGYRO_CONFIG\fP   0x1B"
.br
.ti -1c
.RI "#define \fBACCEL_CONFIG\fP   0x1C"
.br
.ti -1c
.RI "#define \fBFF_THR\fP   0x1D"
.br
.ti -1c
.RI "#define \fBFF_DUR\fP   0x1E"
.br
.ti -1c
.RI "#define \fBMOT_THR\fP   0x1F"
.br
.ti -1c
.RI "#define \fBMOT_DUR\fP   0x20"
.br
.ti -1c
.RI "#define \fBZRMOT_THR\fP   0x21"
.br
.ti -1c
.RI "#define \fBZRMOT_DUR\fP   0x22"
.br
.ti -1c
.RI "#define \fBFIFO_EN\fP   0x23"
.br
.ti -1c
.RI "#define \fBI2C_MST_CTRL\fP   0x24"
.br
.ti -1c
.RI "#define \fBI2C_SLV0_ADDR\fP   0x25"
.br
.ti -1c
.RI "#define \fBI2C_SLV0_REG\fP   0x26"
.br
.ti -1c
.RI "#define \fBI2C_SLV0_CTRL\fP   0x27"
.br
.ti -1c
.RI "#define \fBI2C_SLV1_ADDR\fP   0x28"
.br
.ti -1c
.RI "#define \fBI2C_SLV1_REG\fP   0x29"
.br
.ti -1c
.RI "#define \fBI2C_SLV1_CTRL\fP   0x2A"
.br
.ti -1c
.RI "#define \fBI2C_SLV2_ADDR\fP   0x2B"
.br
.ti -1c
.RI "#define \fBI2C_SLV2_REG\fP   0x2C"
.br
.ti -1c
.RI "#define \fBI2C_SLV2_CTRL\fP   0x2D"
.br
.ti -1c
.RI "#define \fBI2C_SLV3_ADDR\fP   0x2E"
.br
.ti -1c
.RI "#define \fBI2C_SLV3_REG\fP   0x2F"
.br
.ti -1c
.RI "#define \fBI2C_SLV3_CTRL\fP   0x30"
.br
.ti -1c
.RI "#define \fBI2C_SLV4_ADDR\fP   0x31"
.br
.ti -1c
.RI "#define \fBI2C_SLV4_REG\fP   0x32"
.br
.ti -1c
.RI "#define \fBI2C_SLV4_DO\fP   0x33"
.br
.ti -1c
.RI "#define \fBI2C_SLV4_CTRL\fP   0x34"
.br
.ti -1c
.RI "#define \fBI2C_SLV4_DI\fP   0x35"
.br
.ti -1c
.RI "#define \fBI2C_MST_STATUS\fP   0x36"
.br
.ti -1c
.RI "#define \fBINT_PIN_CFG\fP   0x37"
.br
.ti -1c
.RI "#define \fBINT_ENABLE\fP   0x38"
.br
.ti -1c
.RI "#define \fBDMP_INT_STATUS\fP   0x39"
.br
.ti -1c
.RI "#define \fBINT_STATUS\fP   0x3A"
.br
.ti -1c
.RI "#define \fBACCEL_XOUT_H\fP   0x3B"
.br
.ti -1c
.RI "#define \fBACCEL_XOUT_L\fP   0x3C"
.br
.ti -1c
.RI "#define \fBACCEL_YOUT_H\fP   0x3D"
.br
.ti -1c
.RI "#define \fBACCEL_YOUT_L\fP   0x3E"
.br
.ti -1c
.RI "#define \fBACCEL_ZOUT_H\fP   0x3F"
.br
.ti -1c
.RI "#define \fBACCEL_ZOUT_L\fP   0x40"
.br
.ti -1c
.RI "#define \fBTEMP_OUT_H\fP   0x41"
.br
.ti -1c
.RI "#define \fBTEMP_OUT_L\fP   0x42"
.br
.ti -1c
.RI "#define \fBGYRO_XOUT_H\fP   0x43"
.br
.ti -1c
.RI "#define \fBGYRO_XOUT_L\fP   0x44"
.br
.ti -1c
.RI "#define \fBGYRO_YOUT_H\fP   0x45"
.br
.ti -1c
.RI "#define \fBGYRO_YOUT_L\fP   0x46"
.br
.ti -1c
.RI "#define \fBGYRO_ZOUT_H\fP   0x47"
.br
.ti -1c
.RI "#define \fBGYRO_ZOUT_L\fP   0x48"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_00\fP   0x49"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_01\fP   0x4A"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_02\fP   0x4B"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_03\fP   0x4C"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_04\fP   0x4D"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_05\fP   0x4E"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_06\fP   0x4F"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_07\fP   0x50"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_08\fP   0x51"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_09\fP   0x52"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_10\fP   0x53"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_11\fP   0x54"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_12\fP   0x55"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_13\fP   0x56"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_14\fP   0x57"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_15\fP   0x58"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_16\fP   0x59"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_17\fP   0x5A"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_18\fP   0x5B"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_19\fP   0x5C"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_20\fP   0x5D"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_21\fP   0x5E"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_22\fP   0x5F"
.br
.ti -1c
.RI "#define \fBEXT_SENS_DATA_23\fP   0x60"
.br
.ti -1c
.RI "#define \fBMOT_DETECT_STATUS\fP   0x61"
.br
.ti -1c
.RI "#define \fBI2C_SLV0_DO\fP   0x63"
.br
.ti -1c
.RI "#define \fBI2C_SLV1_DO\fP   0x64"
.br
.ti -1c
.RI "#define \fBI2C_SLV2_DO\fP   0x65"
.br
.ti -1c
.RI "#define \fBI2C_SLV3_DO\fP   0x66"
.br
.ti -1c
.RI "#define \fBI2C_MST_DELAY_CTRL\fP   0x67"
.br
.ti -1c
.RI "#define \fBSIGNAL_PATH_RESET\fP   0x68"
.br
.ti -1c
.RI "#define \fBMOT_DETECT_CTRL\fP   0x69"
.br
.ti -1c
.RI "#define \fBUSER_CTRL\fP   0x6A"
.br
.ti -1c
.RI "#define \fBPWR_MGMT_1\fP   0x6B"
.br
.ti -1c
.RI "#define \fBPWR_MGMT_2\fP   0x6C"
.br
.ti -1c
.RI "#define \fBBANK_SEL\fP   0x6D"
.br
.ti -1c
.RI "#define \fBMEM_START_ADDR\fP   0x6E"
.br
.ti -1c
.RI "#define \fBMEM_R_W\fP   0x6F"
.br
.ti -1c
.RI "#define \fBDMP_CFG_1\fP   0x70"
.br
.ti -1c
.RI "#define \fBDMP_CFG_2\fP   0x71"
.br
.ti -1c
.RI "#define \fBFIFO_COUNTH\fP   0x72"
.br
.ti -1c
.RI "#define \fBFIFO_COUNTL\fP   0x73"
.br
.ti -1c
.RI "#define \fBFIFO_R_W\fP   0x74"
.br
.ti -1c
.RI "#define \fBWHO_AM_I\fP   0x75"
.br
.ti -1c
.RI "#define \fBMPU6050_GYRO_CONFIG\fP   0x1B"
.br
.ti -1c
.RI "#define \fBMPU6050_READ\fP   0xD1"
.br
.ti -1c
.RI "#define \fBMPU6050_WRITE\fP   0xD0"
.br
.ti -1c
.RI "#define \fBMPU6050_ACCEL_CONFIG\fP   0x1C"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACCEL_CONFIG   0x1C"

.PP
Definition at line 33 of file mpu6050_reg\&.h\&.
.SS "#define ACCEL_XOUT_H   0x3B"

.PP
Definition at line 64 of file mpu6050_reg\&.h\&.
.SS "#define ACCEL_XOUT_L   0x3C"

.PP
Definition at line 65 of file mpu6050_reg\&.h\&.
.SS "#define ACCEL_YOUT_H   0x3D"

.PP
Definition at line 66 of file mpu6050_reg\&.h\&.
.SS "#define ACCEL_YOUT_L   0x3E"

.PP
Definition at line 67 of file mpu6050_reg\&.h\&.
.SS "#define ACCEL_ZOUT_H   0x3F"

.PP
Definition at line 68 of file mpu6050_reg\&.h\&.
.SS "#define ACCEL_ZOUT_L   0x40"

.PP
Definition at line 69 of file mpu6050_reg\&.h\&.
.SS "#define BANK_SEL   0x6D"

.PP
Definition at line 113 of file mpu6050_reg\&.h\&.
.SS "#define CONFIG   0x1A"

.PP
Definition at line 31 of file mpu6050_reg\&.h\&.
.SS "#define DMP_CFG_1   0x70"

.PP
Definition at line 116 of file mpu6050_reg\&.h\&.
.SS "#define DMP_CFG_2   0x71"

.PP
Definition at line 117 of file mpu6050_reg\&.h\&.
.SS "#define DMP_INT_STATUS   0x39"

.PP
Definition at line 62 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_00   0x49"

.PP
Definition at line 78 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_01   0x4A"

.PP
Definition at line 79 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_02   0x4B"

.PP
Definition at line 80 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_03   0x4C"

.PP
Definition at line 81 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_04   0x4D"

.PP
Definition at line 82 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_05   0x4E"

.PP
Definition at line 83 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_06   0x4F"

.PP
Definition at line 84 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_07   0x50"

.PP
Definition at line 85 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_08   0x51"

.PP
Definition at line 86 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_09   0x52"

.PP
Definition at line 87 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_10   0x53"

.PP
Definition at line 88 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_11   0x54"

.PP
Definition at line 89 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_12   0x55"

.PP
Definition at line 90 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_13   0x56"

.PP
Definition at line 91 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_14   0x57"

.PP
Definition at line 92 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_15   0x58"

.PP
Definition at line 93 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_16   0x59"

.PP
Definition at line 94 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_17   0x5A"

.PP
Definition at line 95 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_18   0x5B"

.PP
Definition at line 96 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_19   0x5C"

.PP
Definition at line 97 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_20   0x5D"

.PP
Definition at line 98 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_21   0x5E"

.PP
Definition at line 99 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_22   0x5F"

.PP
Definition at line 100 of file mpu6050_reg\&.h\&.
.SS "#define EXT_SENS_DATA_23   0x60"

.PP
Definition at line 101 of file mpu6050_reg\&.h\&.
.SS "#define FF_DUR   0x1E"

.PP
Definition at line 35 of file mpu6050_reg\&.h\&.
.SS "#define FF_THR   0x1D"

.PP
Definition at line 34 of file mpu6050_reg\&.h\&.
.SS "#define FIFO_COUNTH   0x72"

.PP
Definition at line 118 of file mpu6050_reg\&.h\&.
.SS "#define FIFO_COUNTL   0x73"

.PP
Definition at line 119 of file mpu6050_reg\&.h\&.
.SS "#define FIFO_EN   0x23"

.PP
Definition at line 40 of file mpu6050_reg\&.h\&.
.SS "#define FIFO_R_W   0x74"

.PP
Definition at line 120 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_CONFIG   0x1B"

.PP
Definition at line 32 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_XOUT_H   0x43"

.PP
Definition at line 72 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_XOUT_L   0x44"

.PP
Definition at line 73 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_YOUT_H   0x45"

.PP
Definition at line 74 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_YOUT_L   0x46"

.PP
Definition at line 75 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_ZOUT_H   0x47"

.PP
Definition at line 76 of file mpu6050_reg\&.h\&.
.SS "#define GYRO_ZOUT_L   0x48"

.PP
Definition at line 77 of file mpu6050_reg\&.h\&.
.SS "#define I2C_MST_CTRL   0x24"

.PP
Definition at line 41 of file mpu6050_reg\&.h\&.
.SS "#define I2C_MST_DELAY_CTRL   0x67"

.PP
Definition at line 107 of file mpu6050_reg\&.h\&.
.SS "#define I2C_MST_STATUS   0x36"

.PP
Definition at line 59 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV0_ADDR   0x25"

.PP
Definition at line 42 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV0_CTRL   0x27"

.PP
Definition at line 44 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV0_DO   0x63"

.PP
Definition at line 103 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV0_REG   0x26"

.PP
Definition at line 43 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV1_ADDR   0x28"

.PP
Definition at line 45 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV1_CTRL   0x2A"

.PP
Definition at line 47 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV1_DO   0x64"

.PP
Definition at line 104 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV1_REG   0x29"

.PP
Definition at line 46 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV2_ADDR   0x2B"

.PP
Definition at line 48 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV2_CTRL   0x2D"

.PP
Definition at line 50 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV2_DO   0x65"

.PP
Definition at line 105 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV2_REG   0x2C"

.PP
Definition at line 49 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV3_ADDR   0x2E"

.PP
Definition at line 51 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV3_CTRL   0x30"

.PP
Definition at line 53 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV3_DO   0x66"

.PP
Definition at line 106 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV3_REG   0x2F"

.PP
Definition at line 52 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV4_ADDR   0x31"

.PP
Definition at line 54 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV4_CTRL   0x34"

.PP
Definition at line 57 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV4_DI   0x35"

.PP
Definition at line 58 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV4_DO   0x33"

.PP
Definition at line 56 of file mpu6050_reg\&.h\&.
.SS "#define I2C_SLV4_REG   0x32"

.PP
Definition at line 55 of file mpu6050_reg\&.h\&.
.SS "#define INT_ENABLE   0x38"

.PP
Definition at line 61 of file mpu6050_reg\&.h\&.
.SS "#define INT_PIN_CFG   0x37"

.PP
Definition at line 60 of file mpu6050_reg\&.h\&.
.SS "#define INT_STATUS   0x3A"

.PP
Definition at line 63 of file mpu6050_reg\&.h\&.
.SS "#define MEM_R_W   0x6F"

.PP
Definition at line 115 of file mpu6050_reg\&.h\&.
.SS "#define MEM_START_ADDR   0x6E"

.PP
Definition at line 114 of file mpu6050_reg\&.h\&.
.SS "#define MOT_DETECT_CTRL   0x69"

.PP
Definition at line 109 of file mpu6050_reg\&.h\&.
.SS "#define MOT_DETECT_STATUS   0x61"

.PP
Definition at line 102 of file mpu6050_reg\&.h\&.
.SS "#define MOT_DUR   0x20"

.PP
Definition at line 37 of file mpu6050_reg\&.h\&.
.SS "#define MOT_THR   0x1F"

.PP
Definition at line 36 of file mpu6050_reg\&.h\&.
.SS "#define MPU6050_ACCEL_CONFIG   0x1C"

.PP
Definition at line 125 of file mpu6050_reg\&.h\&.
.SS "#define MPU6050_GYRO_CONFIG   0x1B"

.PP
Definition at line 122 of file mpu6050_reg\&.h\&.
.SS "#define MPU6050_READ   0xD1"

.PP
Definition at line 123 of file mpu6050_reg\&.h\&.
.SS "#define MPU6050_WRITE   0xD0"

.PP
Definition at line 124 of file mpu6050_reg\&.h\&.
.SS "#define PWR_MGMT_1   0x6B"

.PP
Definition at line 111 of file mpu6050_reg\&.h\&.
.SS "#define PWR_MGMT_2   0x6C"

.PP
Definition at line 112 of file mpu6050_reg\&.h\&.
.SS "#define SIGNAL_PATH_RESET   0x68"

.PP
Definition at line 108 of file mpu6050_reg\&.h\&.
.SS "#define SMPLRT_DIV   0x19"

.PP
Definition at line 30 of file mpu6050_reg\&.h\&.
.SS "#define TEMP_OUT_H   0x41"

.PP
Definition at line 70 of file mpu6050_reg\&.h\&.
.SS "#define TEMP_OUT_L   0x42"

.PP
Definition at line 71 of file mpu6050_reg\&.h\&.
.SS "#define USER_CTRL   0x6A"

.PP
Definition at line 110 of file mpu6050_reg\&.h\&.
.SS "#define WHO_AM_I   0x75"

.PP
Definition at line 121 of file mpu6050_reg\&.h\&.
.SS "#define X_FINE_GAIN   0x03"

.PP
Definition at line 15 of file mpu6050_reg\&.h\&.
.SS "#define XA_OFFS_H   0x06"

.PP
Definition at line 18 of file mpu6050_reg\&.h\&.
.SS "#define XA_OFFS_L_TC   0x07"

.PP
Definition at line 19 of file mpu6050_reg\&.h\&.
.SS "#define XG_OFFS_TC   0x00"

.PP
Definition at line 12 of file mpu6050_reg\&.h\&.
.SS "#define XG_OFFS_USRH   0x13"

.PP
Definition at line 24 of file mpu6050_reg\&.h\&.
.SS "#define XG_OFFS_USRL   0x14"

.PP
Definition at line 25 of file mpu6050_reg\&.h\&.
.SS "#define Y_FINE_GAIN   0x04"

.PP
Definition at line 16 of file mpu6050_reg\&.h\&.
.SS "#define YA_OFFS_H   0x08"

.PP
Definition at line 20 of file mpu6050_reg\&.h\&.
.SS "#define YA_OFFS_L_TC   0x09"

.PP
Definition at line 21 of file mpu6050_reg\&.h\&.
.SS "#define YG_OFFS_TC   0x01"

.PP
Definition at line 13 of file mpu6050_reg\&.h\&.
.SS "#define YG_OFFS_USRH   0x15"

.PP
Definition at line 26 of file mpu6050_reg\&.h\&.
.SS "#define YG_OFFS_USRL   0x16"

.PP
Definition at line 27 of file mpu6050_reg\&.h\&.
.SS "#define Z_FINE_GAIN   0x05"

.PP
Definition at line 17 of file mpu6050_reg\&.h\&.
.SS "#define ZA_OFFS_H   0x0A"

.PP
Definition at line 22 of file mpu6050_reg\&.h\&.
.SS "#define ZA_OFFS_L_TC   0x0B"

.PP
Definition at line 23 of file mpu6050_reg\&.h\&.
.SS "#define ZG_OFFS_TC   0x02"

.PP
Definition at line 14 of file mpu6050_reg\&.h\&.
.SS "#define ZG_OFFS_USRH   0x17"

.PP
Definition at line 28 of file mpu6050_reg\&.h\&.
.SS "#define ZG_OFFS_USRL   0x18"

.PP
Definition at line 29 of file mpu6050_reg\&.h\&.
.SS "#define ZRMOT_DUR   0x22"

.PP
Definition at line 39 of file mpu6050_reg\&.h\&.
.SS "#define ZRMOT_THR   0x21"

.PP
Definition at line 38 of file mpu6050_reg\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
