.TH "Src/utils/printf_config.c" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/utils/printf_config.c
.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBITM_SendString\fP (char *data, int len)"
.br
.ti -1c
.RI "int \fB_write\fP (int file, char *data, int len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int _write (int file, char * data, int len)"

.PP
Definition at line 23 of file printf_config\&.c\&.
.SS "int ITM_SendString (char * data, int len)"

.PP
Definition at line 12 of file printf_config\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
