.TH "Inc/robot/robot.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/robot/robot.h
.SH SYNOPSIS
.br
.PP
\fC#include 'robo_init\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBgo\fP (int \fBsteps\fP, float \fBangle\fP)"
.br
.ti -1c
.RI "void \fBmove_leg\fP (int \fBsteps\fP, float \fBangle\fP)"
.br
.ti -1c
.RI "void \fBmove_steering\fP (int \fBsteps\fP, float \fBangle\fP)"
.br
.ti -1c
.RI "void \fBcalculate_datas\fP (void)"
.br
.ti -1c
.RI "void \fBcalculate_robot_angle\fP (void)"
.br
.ti -1c
.RI "bool \fBrewind\fP (void)"
.br
.ti -1c
.RI "bool \fBplay\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void calculate_datas (void)"

.PP
Definition at line 158 of file robot\&.cpp\&.
.SS "void calculate_robot_angle (void)"
Alternate code to calculate robot_angle using IMU 
.PP
Definition at line 121 of file robot\&.cpp\&.
.SS "bool go (int steps, float angle)"

.PP
Definition at line 24 of file robot\&.cpp\&.
.SS "void move_leg (int steps, float angle)"

.PP
Definition at line 47 of file robot\&.cpp\&.
.SS "void move_steering (int steps, float angle)"

.PP
Definition at line 60 of file robot\&.cpp\&.
.SS "bool play (void)"

.PP
Definition at line 166 of file robot\&.cpp\&.
.SS "bool rewind (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
