.TH "Inc/robot/robo_init.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/robot/robo_init.h
.SH SYNOPSIS
.br
.PP
\fC#include 'leg\&.h'\fP
.br
\fC#include 'steering\&.h'\fP
.br
\fC#include 'tim\&.h'\fP
.br
\fC#include 'usart\&.h'\fP
.br
\fC#include 'gpio\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'vec3\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrobo_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void robo_init (void)"

.PP
Definition at line 17 of file robo_init\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
