.TH "Inc/devs/steering.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/devs/steering.h
.SH SYNOPSIS
.br
.PP
\fC#include 'motor\&.h'\fP
.br
\fC#include 'encoder\&.h'\fP
.br
\fC#include 'pid\&.h'\fP
.br
\fC#include 'limit_switch\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsteering\fP"
.br
.RI "Provide control over steering of the horse\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
