.TH "Inc/periphs/tim.h" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/periphs/tim.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_TIM1_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_TIM2_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_TIM3_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_TIM8_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_TIM_MspPostInit\fP (TIM_HandleTypeDef *htim)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim1\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim2\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim3\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim8\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)"
TIM8 GPIO Configuration
.PP
PC7 ------> TIM8_CH2 PC8 ------> TIM8_CH3 PC9 ------> TIM8_CH4
.PP
Definition at line 314 of file tim\&.c\&.
.SS "void MX_TIM1_Init (void)"

.PP
Definition at line 53 of file tim\&.c\&.
.SS "void MX_TIM2_Init (void)"

.PP
Definition at line 86 of file tim\&.c\&.
.SS "void MX_TIM3_Init (void)"

.PP
Definition at line 118 of file tim\&.c\&.
.SS "void MX_TIM8_Init (void)"

.PP
Definition at line 150 of file tim\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "TIM_HandleTypeDef htim1"
File Name : \fBTIM\&.h\fP Description : This file provides code for the configuration of the TIM instances\&.
.PP
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2019 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&.
.PP
File Name : \fBTIM\&.c\fP Description : This file provides code for the configuration of the TIM instances\&.
.PP
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2019 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.PP
Definition at line 47 of file tim\&.c\&.
.SS "TIM_HandleTypeDef htim2"

.PP
Definition at line 48 of file tim\&.c\&.
.SS "TIM_HandleTypeDef htim3"

.PP
Definition at line 49 of file tim\&.c\&.
.SS "TIM_HandleTypeDef htim8"

.PP
Definition at line 50 of file tim\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
