.TH "Vec2< T >" 3 "Sun May 12 2019" "ROBOCON_2019_HORSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec2< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vec2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec2\fP ()"
.br
.ti -1c
.RI "\fBVec2\fP (T x, T y)"
.br
.ti -1c
.RI "\fBVec2\fP (\fBVec3\fP< T > v)"
.br
.ti -1c
.RI "\fBVec2\fP (\fBVec2\fP &&)=default"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator=\fP (\fBVec2\fP &&)=default"
.br
.ti -1c
.RI "\fB~Vec2\fP ()"
.br
.ti -1c
.RI "T \fBgetX\fP () const"
.br
.ti -1c
.RI "T \fBgetY\fP () const"
.br
.ti -1c
.RI "void \fBsetX\fP (T x)"
.br
.ti -1c
.RI "void \fBsetY\fP (T y)"
.br
.ti -1c
.RI "void \fBset_Values\fP (T x, T y)"
.br
.ti -1c
.RI "\fBVec2\fP \fBmult_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec2\fP \fBmult_EW\fP (\fBVec2\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec2\fP \fBadd_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec2\fP \fBadd_EW\fP (\fBVec2\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec2\fP \fBsub_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec2\fP \fBsub_EW\fP (\fBVec2\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec2\fP \fBdiv_EW\fP (float num)"
.br
.ti -1c
.RI "template<typename T1 > \fBVec2\fP \fBdiv_EW\fP (\fBVec2\fP< T1 > v)"
.br
.ti -1c
.RI "\fBVec2\fP (const \fBVec2\fP &v)"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator=\fP (const \fBVec2\fP &v)"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator+=\fP (const \fBVec2\fP &rhs)"
.br
.ti -1c
.RI "\fBVec2\fP & \fBoperator\-=\fP (const \fBVec2\fP &rhs)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBx_\fP"
.br
.ti -1c
.RI "T \fBy_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBVec2\fP \fBoperator+\fP (\fBVec2\fP lhs, const \fBVec2\fP &rhs)"
.br
.ti -1c
.RI "\fBVec2\fP \fBoperator\-\fP (\fBVec2\fP lhs, const \fBVec2\fP &rhs)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBVec2\fP &first, \fBVec2\fP &second)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class Vec2< T >"

.PP
Definition at line 15 of file vec2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBVec2\fP< T >::\fBVec2\fP ()\fC [inline]\fP"

.PP
Definition at line 18 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP< T >::\fBVec2\fP (T x, T y)\fC [inline]\fP"

.PP
Definition at line 19 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP< T >::\fBVec2\fP (\fBVec3\fP< T > v)\fC [inline]\fP"

.PP
Definition at line 21 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP< T >::\fBVec2\fP (\fBVec2\fP< T > &&)\fC [default]\fP"

.SS "template<class T> \fBVec2\fP< T >::~\fBVec2\fP ()\fC [inline]\fP"

.PP
Definition at line 25 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP< T >::\fBVec2\fP (const \fBVec2\fP< T > & v)\fC [inline]\fP"

.PP
Definition at line 110 of file vec2\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T> \fBVec2\fP \fBVec2\fP< T >::add_EW (float num)\fC [inline]\fP"

.PP
Definition at line 56 of file vec2\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec2\fP \fBVec2\fP< T >::add_EW (\fBVec2\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 65 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP \fBVec2\fP< T >::div_EW (float num)\fC [inline]\fP"

.PP
Definition at line 92 of file vec2\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec2\fP \fBVec2\fP< T >::div_EW (\fBVec2\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 101 of file vec2\&.h\&.
.SS "template<class T> T \fBVec2\fP< T >::getX () const\fC [inline]\fP"

.PP
Definition at line 27 of file vec2\&.h\&.
.SS "template<class T> T \fBVec2\fP< T >::getY () const\fC [inline]\fP"

.PP
Definition at line 28 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP \fBVec2\fP< T >::mult_EW (float num)\fC [inline]\fP"

.PP
Definition at line 38 of file vec2\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec2\fP \fBVec2\fP< T >::mult_EW (\fBVec2\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 47 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP& \fBVec2\fP< T >::operator+= (const \fBVec2\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line 122 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP& \fBVec2\fP< T >::operator\-= (const \fBVec2\fP< T > & rhs)\fC [inline]\fP"

.PP
Definition at line 129 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP& \fBVec2\fP< T >::operator= (\fBVec2\fP< T > &&)\fC [default]\fP"

.SS "template<class T> \fBVec2\fP& \fBVec2\fP< T >::operator= (const \fBVec2\fP< T > & v)\fC [inline]\fP"

.PP
Definition at line 115 of file vec2\&.h\&.
.SS "template<class T> void \fBVec2\fP< T >::print () const\fC [inline]\fP"

.PP
Definition at line 146 of file vec2\&.h\&.
.SS "template<class T> void \fBVec2\fP< T >::set_Values (T x, T y)\fC [inline]\fP"

.PP
Definition at line 32 of file vec2\&.h\&.
.SS "template<class T> void \fBVec2\fP< T >::setX (T x)\fC [inline]\fP"

.PP
Definition at line 29 of file vec2\&.h\&.
.SS "template<class T> void \fBVec2\fP< T >::setY (T y)\fC [inline]\fP"

.PP
Definition at line 30 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP \fBVec2\fP< T >::sub_EW (float num)\fC [inline]\fP"

.PP
Definition at line 74 of file vec2\&.h\&.
.SS "template<class T> template<typename T1 > \fBVec2\fP \fBVec2\fP< T >::sub_EW (\fBVec2\fP< T1 > v)\fC [inline]\fP"

.PP
Definition at line 83 of file vec2\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T> \fBVec2\fP operator+ (\fBVec2\fP< T > lhs, const \fBVec2\fP< T > & rhs)\fC [friend]\fP"

.PP
Definition at line 136 of file vec2\&.h\&.
.SS "template<class T> \fBVec2\fP operator\- (\fBVec2\fP< T > lhs, const \fBVec2\fP< T > & rhs)\fC [friend]\fP"

.PP
Definition at line 141 of file vec2\&.h\&.
.SS "template<class T> void swap (\fBVec2\fP< T > & first, \fBVec2\fP< T > & second)\fC [friend]\fP"

.PP
Definition at line 153 of file vec2\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> T \fBVec2\fP< T >::x_\fC [private]\fP"

.PP
Definition at line 151 of file vec2\&.h\&.
.SS "template<class T> T \fBVec2\fP< T >::y_\fC [private]\fP"

.PP
Definition at line 151 of file vec2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ROBOCON_2019_HORSE from the source code\&.
