#ifndef _DEFINES_H_
#define _DEFINES_H_

#define PI (3.1415926535897932384626433832795)
#define SAMPLE_TIME (10)
#define LEG_MOTOR_MAX_OMEGA (70)
#define STEERING_MOTOR_MAX_OMEGA (7)
#define LEG_TO_MOTOR_RATIO (4)
#define MOTOR_TO_ENCODER_RATIO (1)
#define LEG_TO_ENCODER_RATIO (LEG_TO_MOTOR_RATIO * MOTOR_TO_ENCODER_RATIO)
#define BEARING_TO_STEERING_RATIO (8)
#define BODY_WEIGHT (8)
#define LEG_WEIGHT (1)

#endif // !_DEFINES_H_


